### ISSUE TITLE
ItemBuilder for animated SlideAction

### ISSUE THREAD

**Issue by Solido** [letsar/flutter_slidable#1]
So the idea would be using an itemBuilder for SlideAction that mimics the AnimatedList so we can access the Animation<double> when creating the child. This way I can also animate Opacity in my case.

**Comment by letsar** [comment]
Nice one 😃. Very useful suggestion. I don't think it will be backward compatible though, if I want to keep it simple.

**Comment by Solido** [comment]
If you don't want to break the current API you can use the same trick than color property on Container.

You can set color field only if decoration field is not present.

Maybe you can keep child under SlideAction but make it invalid if this part is not present 

`builder : (Context c, Animation a) {}`

**Comment by letsar** [comment]
What I had in mind about breaking changes, was more about custom slidable delegate. If I want to keep the API simple, I will only expose the builders, and not the widget list anymore for slidable actions.
I plan to work on this today on another branch.
Once I have something working, would you mind telling me what you think?

**Comment by Solido** [comment]
Show me the code when it's done ! It's already in my project, should be straightforward to tell you how the API 'feels' and if I can reach the required effect on my app.

**Comment by Solido** [comment]
I really love the API, when you getting confortable with builder you want them anywhere.
It is transparent with the rest of the Flutter API and the effect I wanted is implemented easily.
What is great is that I can reuse the same code that what I use in AnimatedList.

**Comment by letsar** [comment]
Available on version 0.2.0
