### ISSUE TITLE
Prevent Slidable from staying open

### ISSUE THREAD

**Issue by joeyvanlierop** [letsar/flutter_slidable#105]
Is there any way to make a Slidable widget never stay open/pinned? I would like to create gesture driven list items that run code based on the extent that the Slidable widget is open when it is released, meaning I would never need it to stay open.

**Comment by letsar** [comment]
Can you test your use case with 1.0 and playing with openThreshold to see if it can be done automatically or if I need to add this?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
