### ISSUE TITLE
Lefthand child scrambled when touched outside of item

### ISSUE THREAD

**Issue by jonasbark** [letsar/flutter_slidable#11]
Appeared in Version 0.3.0

```
Slidable(
        key: Key(item.id.toString()),
...
        actionExtentRatio: 0.15,
        delegate: SlidableStrechDelegate(),
        actions: <Widget>[
          Center(child: Text('ID ${item.id}', style: TextStyle(color: Colors.grey)))
        ],
...
      )
```

Slide out look:
![image](https://user-images.githubusercontent.com/1151304/43121116-ebb0e61e-8f1c-11e8-81c5-604e264df6da.png)

When I touch outside (e.g. list scroll):
![image](https://user-images.githubusercontent.com/1151304/43121133-04958658-8f1d-11e8-8794-f32a3cc6041b.png)

**Comment by letsar** [comment]
Fix published in 0.3.1.
