### ISSUE TITLE
How prevent over-sliding?

### ISSUE THREAD

**Issue by remoteportal** [letsar/flutter_slidable#114]
_Thank you VERY much for all your hard work!_

Hey, I've researched but I don't know how to prevent "over-sliding."

After the two drawer rectangles have reached a certain size (say, max=200), it should snap lock, and not allow the rectangles to grow hugely wide.

(I noticed different question/solution I thought was related and tried:

> Slidable( ... actionExtentRatio: 0.1,)

but that just caused the ratio between the two rectangles to be wrong.)

**Comment by letsar** [comment]
Can you test with the 1.0 version?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
