### ISSUE TITLE
change secondaryActions to receive function

### ISSUE THREAD

**Issue by calvinsug** [letsar/flutter_slidable#120]
Hi guys, i just need to implement slideable if user swipe to the right which show 2 menu at the left and it has works perfectly like i want!

But, what i want is, when i swipe my listView to the left, i want to push navigate to another screen? Can we do that with this ?

I have tried to implement GestureDetector with onHorizontalDragUpdate, but it didn't work if i use Slidable in my child

**Comment by letsar** [comment]
We should'nt mix two views with the same scroll direction within the same view.
