### ISSUE TITLE
In the onTap method of the SlideAction button, SlidableState obtained with Slidable. Of (context) is null, so the dimiss operation cannot be performed. Here is the code example

### ISSUE THREAD

**Issue by wj576038874** [letsar/flutter_slidable#121]
class MyHomePage extends StatefulWidget {
  final List<String> items = List.generate(5, (index) {
    return "item$index";
  });

  @override
  State<StatefulWidget> createState() {
    return MyHomePageState();
  }
}

class MyHomePageState extends State<MyHomePage> {
  SlidableController controller = SlidableController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter Slidable Demo'),
      ),
      body: ListView.builder(
        itemCount: widget.items.length,
        itemBuilder: (BuildContext context, int index) {
          return Slidable(
            controller: controller,
            key: ValueKey(index),
            actionPane: SlidableDrawerActionPane(),
            secondaryActions: <Widget>[
              SlideAction(
                closeOnTap: false,
                child: Text("删除"),
                decoration: BoxDecoration(
                    color: Colors.red,
                    borderRadius: BorderRadius.circular(4.0)),
                onTap: () {
                  Slidable.of(context).dismiss();
                },
              ),
            ],
            dismissal: SlidableDismissal(
              onDismissed: (actionType) {
                setState(() {
                  widget.items.removeAt(index);
                });
                print("length${widget.items.length}");
              },
              onWillDismiss: (actionType) {
                return showDialog<bool>(
                    context: context,
                    builder: (context) {
                      return AlertDialog(
                        title: Text('提示？'),
                        content: Text('确定删除该条记录？'),
                        actions: <Widget>[
                          FlatButton(
                            child: Text('取消'),
                            onPressed: () => Navigator.of(context).pop(false),
                          ),
                          FlatButton(
                            child: Text('确定'),
                            onPressed: () => Navigator.of(context).pop(true),
                          ),
                        ],
                      );
                    });
              },
              child: SlidableDrawerDismissal(),
            ),
            child: Container(
              color: Colors.white,
              child: ListTile(
                leading: CircleAvatar(
                  backgroundColor: Colors.indigoAccent,
                  child: Text('${index}'),
                  foregroundColor: Colors.white,
                ),
                title: Text('Tile n°${index}'),
                subtitle: Text('SlidableDrawerDelegate'),
              ),
            ),
          );
        },
      ),
    );
  }
}

**Comment by letsar** [comment]
You call Slidable.of(context) with a context above the Slidable. Thus it doesn't find it.
