### ISSUE TITLE
Slidable.of(context) return null

### ISSUE THREAD

**Issue by Altamill** [letsar/flutter_slidable#122]
Hello, how to programmatically close the currently open listile? #95's solution is not helpful to me, the code is as follows thank you.

              child: ListTile(
                leading: Flex(
                  direction: Axis.vertical,
                  children: <Widget>[
                    Expanded(
                      flex: 1,
                      child: Icon(
                        Icons.warning,
                        color: Color(0xFFfaad14)
                      ),
                    ),
                  ],
                ),

                title: Text(items[index]['level']+'：'+items[index]['title']),

                subtitle: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Text('IP：'+items[index]['ip']),
                    Text('应用：'+items[index]['appName']),
                    Text('时间：'+items[index]['time']),
                  ],
                ),

                trailing: Column(
                  children: <Widget>[
                    Expanded(
                      flex: 1,
                      child: Flex(
                        mainAxisSize: MainAxisSize.min,
                        direction: Axis.horizontal,
                        children: <Widget>[
                          Badge(
                            toAnimate: false,
                            badgeContent: Text(items[index]['total'], style: TextStyle(color: Colors.white)),
                          ),
                          Icon(items[index]['state'] == 'warning' ? Icons.notifications_active : Icons.notifications_off),
                        ],
                      ),
                    )
                  ],
                ),

                onTap: () {
                  showAlarmDetail(items[index]);
                },
              ),

              void showAlarmDetail(Map<String, String> item) {
                print(Slidable.of(context));
                Navigator.of(context).pushNamed('alarmDetail', arguments: item);
              }

**Comment by nicolasvahidzein** [comment]
Can you write something instead of posting random code?

**Comment by Altamill** [comment]
`print(Slidable.of(context));`
return null

**Comment by jobehi** [comment]
Same goes for me, in a child widget, Slidable.of(context).open() and Slidable.of(context) don't work because Slidable.of(context) always returns null

**Comment by letsar** [comment]
I don't have a lot of time so I will be quick. I extrapolate, because I don't have the full code, but I think you are in a StatefulWidget and so, the context you're referring to in showAlarmDetail does'n know anything about the Slidable you put into your build method. It's like Scaffold, you have to pass a context which is below the Slidable in the widget tree.

**Comment by Altamill** [comment]
You are right. I can get the context after I repackage listview! Thank!
