### ISSUE TITLE
[Feature Request] Tap/Press Slidable for get Slide Action

### ISSUE THREAD

**Issue by septiandik** [letsar/flutter_slidable#123]
Example like this
![YouCut_20200301_043630155](https://user-images.githubusercontent.com/61361087/75615546-8f33e480-5b77-11ea-8f3c-16c3c0bd2059.gif)

**Comment by hasansahinnn** [comment]
https://github.com/letsar/flutter_slidable/issues/191

**Comment by letsar** [comment]
It can be done in 1.0. You just have to get the SlidableController inside the Slidable's child with Slidable.of(context), and call openStartActionPane or openEndActionPane methods.
