### ISSUE TITLE
how to know action index?

### ISSUE THREAD

**Issue by lionnner** [letsar/flutter_slidable#125]
For exg:
when slidableController onSlideIsOpenChanged call open, how can i get the opened index? 
ListView.builder(
      padding: EdgeInsets.only(bottom: MediaQuery.of(context).padding.bottom),
      itemCount: items.length,
      itemBuilder: (context, index) => Slidable(
        key: UniqueKey(),
        dismissal: SlidableDismissal(
          child: SlidableDrawerDismissal(),
          onDismissed: (actionType) => delete(index),
        ),
        controller: slidableController,
        child: _buildItemWidget(
          items[index],
          showStatus: items[index].statusMsg.isNotEmpty,
        ),
        secondaryActions: <Widget>[
          SlideAction(
            color: WukongColors.red,
            child: Text(
              'Delete',
              style: Styles.white(16),
            ),
            onTap: () {
              delete(index);
            },
          ),
        ],
        actionPane: SlidableDrawerActionPane(),
      ),
    );

**Comment by coldembrace** [comment]
You can just pass your model as a parameter, e.g.:
```
Widget _buildItem(WordModel item) {
        return Slidable(
            actionPane: SlidableDrawerActionPane(),
            actionExtentRatio: 0.25,
            child: Card(
              //...
          ),
          actions: <Widget>[
            ],
            secondaryActions: <Widget>[
              IconSlideAction(
                caption: 'Delete',
                color: Colors.red,
                icon: Icons.delete,
                onTap: () => _deleteSingleItem(item), // pass item your item here
              ),
            ]
        );
      }
```

If you need only the index of an item, I suggest to add an appropriate field inside your data model. Then you'll be able to pass it inside your `onTap` callback: 
`onTap: () => _deleteSingleItem(item.index),`

**Comment by XinleZhou2018** [comment]
do you solve this problem

**Comment by letsar** [comment]
The solution of @coldembrace is correct.
