### ISSUE TITLE
Width of the action(different sizes) 

### ISSUE THREAD

**Issue by ITaran7237** [letsar/flutter_slidable#127]
Thank you for cool lib) I have a question, can I change the width of the action independently from each other, for example, the left action is width 100, and the right action has an icon of 20? Or is this impossible? thanks

**Comment by icespring** [comment]
same needs

**Comment by letsar** [comment]
I'm working on a full refactoring but it will take time. Thanks for this idea!

**Comment by troyanskiy** [comment]
Hello @letsar 
Do you have any idea when that can be implemented?
Also what would be cool is to support dynamic size adjustment.
Ex:
We have to secondary actions:
* Add to favorites
* Add to order
And when we are adding to order the widget will be changed to bigger.
![image](https://user-images.githubusercontent.com/1538862/81581079-86992f00-93ae-11ea-96b6-602da87248df.png)
![image](https://user-images.githubusercontent.com/1538862/81581114-93b61e00-93ae-11ea-81ae-0ee03bd04f1a.png)

**Comment by 594904020** [comment]
Same needs

**Comment by chuongdevJC** [comment]
same needs

**Comment by letsar** [comment]
It should be possible to do this with the 1.0 version. Can you try it?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
