### ISSUE TITLE
secondary showAllActionsThreshold

### ISSUE THREAD

**Issue by visit1985** [letsar/flutter_slidable#129]
Currently it is not possible to set an equal drag distance for left and right slide if the number of actions and secondaryActions differs. It would be helpful to have different showAllActionsThreshold for that case.

Maybe the default value for a secondaryShowAllActionsThreshold could be derived from showAllActionsThreshold.

**Comment by letsar** [comment]
Will be possible in the refactoring

**Comment by letsar** [comment]
It's now possible to set a different threshold for the start and end action panes.
