### ISSUE TITLE
How to enable only one-directional gesture detector?

### ISSUE THREAD

**Issue by BobOKFine** [letsar/flutter_slidable#130]
I have a list of Slidables inside a TabBarView (Page 1). My intention is that swiping the Slidable to the right would reveal the hidden menu (primary actions) while swiping the Slidable to the left would move the whole page to the left and thus reveal Page 2 of the TabBarView (no secondary actions of the Slidable needed). How can I achieve this? It seems that now the Slidable has consumed all the horizontal gestures (both left and right) and swiping to the left does nothing (the TabBarView can only be moved by dragging the area outside the Slidables). I've tried to change the source code (the "content = GestureDetector" part) but I don't know exactly how... Please send help. Thanks.

**Comment by letsar** [comment]
Don't stack two views with the same scroll directions
