### ISSUE TITLE
Item get disposed and recreated while sliding start and sliding end, The future builder inside the item get recalled

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [letsar/flutter_slidable#132]

**Comment by Riyad95** [comment]
same issue, here did you find a solution?
the problem: when sliding the item flickers twice, once on the start of the sliding and one upon finishing it. this happens when there is a future builder inside the tree, because sliding a list item disposes then re-creates it.

**Comment by letsar** [comment]
Dupe of #51
