### ISSUE TITLE
Parameter Missing - closeOnTap

### ISSUE THREAD

**Issue by RichieMcMullen** [letsar/flutter_slidable#133]
The ```closeOnTap``` parameter is not available to use.

**Comment by dominic-deantonio** [comment]
If you have a child which receives taps, you can call `SlidableController.activeState?.close()`.

**Comment by RichieMcMullen** [comment]
Thanks, will try that!

**Comment by vuthasothea** [comment]
> If your Slidable has a child which receives taps, you can call `SlidableController.activeState?.close()`.
> 
> Edit: I should mention the controller needs to be assigned as the `Slidable.controller` parameter.

Great thank
