### ISSUE TITLE
RTL Support Needed

### ISSUE THREAD

**Issue by ozburo** [letsar/flutter_slidable#134]
We should implement RTL support for this widget like do w/ Dismissible. 

Essentially the order of the `actions` and `secondaryActions` should be reversed.

**Comment by letsar** [comment]
You're right!

**Comment by letsar** [comment]
Can you test it with 1.0 version?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
