### ISSUE TITLE
The future of Slidable

### ISSUE THREAD

**Issue by letsar** [letsar/flutter_slidable#135]
Hi everybody!

Some of you wondered why this package is not updated enough, why the issues keep growing, why don't I merge the PR. The answer is simple: I don't have enough time.
I'm working full time in a company and sadly I cannot take some professional time to maintain this package. Moreover I'm now the father of a great baby who needs they parent a lot, thus almost all my free time go to my child. And the rest of the time I try to sleep 😅.
I want to update and maintain this package, I want to help the Flutter community, but for now I'm doing it for free and when I can find some time. My dream would be to be able to work on these packages one day per week, but I need to win at the lottery for this 😅.

That's all for the context. Now let's talk about the future of Slidable.

There are some things in this package I need to rework. For example, we cannot for the moment have a type of animation for the primary actions and another one for the secondary actions. Also all actions must have the same extent and some of you need to be able to set one action to 80% of the pane and the other one to 20%. These kind of changes involve a lot of work. In fact it's better for me to rework all the package, in order to improve the code, to take all the evolution that need a lot of changes into account.

When I created this package, I wanted to help the user by providing an example of a widget for an action: the SlideAction. For me it was just an example or a simple out-of-the-box widget, because any widget can do the job. But I've got some issues concerning this part of the package and I addressed some of them. Now I wonder if it makes sense to keep the SlideAction into this package. What do you think? Should I keep it in this package, remove it and let the developer create its own action which will fit his needs or create another package just for them?

Also, since I don't have the time to go through all the issues. Can someone list me all the enhancements the people have asked that I should take into account for the reworking?

Thank you all.

**Comment by kenthinson** [comment]
@letsar Would you be open to having a different developer with more time take over the project?

**Comment by orestesgaolin** [comment]
I think that "taking over" might not be the best option. However, would you consider to "delegate" some of the work to someone else? Provided you have some kind of vision for the future of the package you could create several small issues with a proper label (e.g. `help-wanted`) and basic specification. I bet there could be few people willing to implement some of them in their spare time. 

For instance I would happily contribute few small features (like extra padding property or another `actionPane` type) but it would be much more reasonable if they were aligned with your plans for the package.

**Comment by kenthinson** [comment]
@orestesgaolin The reason I suggest someone with time "take over" the project is in letsar own words he has no time. As an example I posted 13 days ago and no response. 7 pull requests sitting without activity ect. A new baby sucks time like crazy. Not trying to badmouth letsar I think he has all the right reasons to be busy :) But I don't think leaving the project without someone who can commit changes is the right call.

**Comment by letsar** [comment]
Hello @kenthinson I'm not giving up this project at all. It was not what I meant. But for the moment I just wanted you to know that I don't have the proper time to deal with all the issues and pull requests. I gave my free time for this. To continue as much as want, I don't have any choice for the moment. Either I find more free time (the little I have I put it in another project for the moment) and I stop sleeping, or I quit my job for doing something I'm not paid. None of the option is suitable for me. So for the moment, I'm sorry but you'll need to be patient.

@orestesgaolin I like you suggestion, but I need to put down my ideas first 😄

**Comment by orestesgaolin** [comment]
@letsar did you consider applying for GitHub Sponsorship? 

If you could create several sample issues that have "help-wanted" or "good-first-issue" labels then I would consider helping out with that. I had to tweak slidable a bit to my needs and maybe I could help with that. In the worst case they will just wait for somebody else.

**Comment by letsar** [comment]
@orestesgaolin Yes I did apply, but for now I'm waiting for my Stripe account to be validated.

Thanks for the ideas, I would think about these sample issues.

**Comment by letsar** [comment]
Since the refactoring is done and there is now a published preview, I can close this. It was long, but the refactoring was a necessary "evil". Now you can get the SlidableController from inside a Slidable's child and listen to various event. It's more powerful and flexible. I also added a lot more tests. I hope you'll find the new API way better.
