### ISSUE TITLE
Slidable assumes its full screen width?

### ISSUE THREAD

**Issue by SogoGolf** [letsar/flutter_slidable#138]
hi, am having a problem whereby Slidable is set inside a Container, that has padding. If the user goes to delete a row - then the width of the slidable goes over both sides of the Container and all the way out to the screen's full width/edges. Can this be changed via properties ? Here is a video to show what I mean:

![2020-05-30_16-18-43 (1)](https://user-images.githubusercontent.com/19580787/83321251-b5117800-a291-11ea-9d87-209d32e6f2ab.gif)

**Comment by xuejmnet** [comment]
you can use ClipRRect to wrap item
`AppCard(
      child: ClipRRect(
        borderRadius: BorderRadius.circular(App.w(8)),
        child: Slidable(
          key: Key(widget.model.express.id.toString()),
          actionPane: SlidableDrawerActionPane(),
          actionExtentRatio: 0.25,
          child: child,
          secondaryActions: <Widget>[
            IconSlideAction(
            ),
            IconSlideAction(
            ),
          ],
        ),
      ),
    )`

**Comment by SogoGolf** [comment]
perfect! many thanks

**Comment by MuhammadRauf202** [comment]
perfect, many many Thanks.

**Comment by 1SagarSharma7** [comment]
Thanks
