### ISSUE TITLE
Animate remove row after tapping delete, similar to Dismissible

### ISSUE THREAD

**Issue by ghunter99** [letsar/flutter_slidable#14]
Thanks for doing such an great job with this widget.
One of the most common iOS actions is to slide a row across and then tap on delete.
Then (after possibly prompting the user) programmatically triggering an animation that removes the row (similar to the way the Dismissible widget animates).
Any thoughts about how one might go about implementing this functionality?

**Comment by letsar** [comment]
Hi @ghunter99,
Thanks for your feedback :blush:.

I've just started to work on the **slide to dismiss** feature. 
Once finished, I could then add a `dismiss` method on the `SlidableState` that will trigger this animation.

Without this feature, for now, I have no idea how someone would do that without implementing what I'm working on :pensive:.

**Comment by ghunter99** [comment]
:thumbsup:  
...would be great if you are able to implement a dismiss method.
I appreciate that implementing this stuff is quite nuanced, has lots of edge cases & and takes quite a bit of skill to do well

**Comment by letsar** [comment]
With version 0.4.0 you should be able to do this like this:

```dart
slideToDismissDelegate: new SlideToDismissDrawerDelegate(
        onWillDismiss
            : (actionType) {
                return showDialog<bool>(
                  context: context,
                  builder: (context) {
                    return new AlertDialog(
                      title: new Text('Delete'),
                      content: new Text('Item will be deleted'),
                      actions: <Widget>[
                        new FlatButton(
                          child: new Text('Cancel'),
                          onPressed: () => Navigator.of(context).pop(false),
                        ),
                        new FlatButton(
                          child: new Text('Ok'),
                          onPressed: () => Navigator.of(context).pop(true),
                        ),
                      ],
                    );
                  },
                );
              },
        onDismissed: (actionType) {
          _showSnackBar(
              context,
              actionType == SlideActionType.primary
                  ? 'Dismiss Archive'
                  : 'Dimiss Delete');
          setState(() {
            items.removeAt(index);
          });
        },
      ),
```

The `slideToDismissDelegate` is a new argument in the `Slidable` constructors.

**Comment by ghunter99** [comment]
Thanks for this. Great work! ...just read your Medium story "Slidable: A Flutter Story". I'm blown away by Flutter too!

**Comment by fducha** [comment]
Hi! Why did you close the issue? The feature still isn't implemented. There is no animation when Slidable is removed from listview.
