### ISSUE TITLE
Unexpected behaviour of the Slidable.enabled flag

### ISSUE THREAD

**Issue by denis-evteev** [letsar/flutter_slidable#142]
First of all, thanks a lot for making this awesome plugin!

Recently I noticed an issue with an app I’m working on — sometimes widgets that I wrapped into slidables lost their states. First I didn’t attribute that issue to this plugin, however, a thorough investigation revealed that unfortunately the root cause of it lied in the way how `Slidable` reacts on toggling the `enabled` flag.

I noticed that depending on [this](https://github.com/letsar/flutter_slidable/blob/master/lib/src/widgets/slidable.dart#L898) condition, the `Slidable` may or may not wrap its child widget into a `GestureDetector`. While it definitely makes sense to check whether the slidable has any actions prior to enabling gesture detection, I doubt that it’s a good idea to change the subtree structure when the only thing that actually changes is the `enabled` flag. In either case, doing that causes Flutter to re-create the whole subtree beneath the `Slidable` widget leading to all widgets in that subtree losing their corresponding states.

This is not quite the effect I expected to see when I only tried to temporarily enable or disable the slidable actions. I suppose that a better option to handle that would be to simply change the attributes of the `GestureDetector`’s wrapper as I proposed in [this](https://github.com/letsar/flutter_slidable/pull/141) PR. This way the subtree structure remains the same, while gesture detection is ignored when the `Slidable.enabled` flag is set to `false`.

**Comment by MobiliteDev** [comment]
Same problem here, when I change the enable flag all statefulWidget lose state and rebuild.

**Comment by letsar** [comment]
I will take this into account in my refactoring.

**Comment by letsar** [comment]
Can you try it with 1.0 version?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
