### ISSUE TITLE
it´s not possible to hidden the IconSlideAction()

### ISSUE THREAD

**Issue by robertoltrocha** [letsar/flutter_slidable#143]
Hi,

In some situations, I need to hide IconSlideAction () and there is no such option. I place a Container () in an attempt to hide, but there is a space white in the Widget's location.
Is it possible to implement this improvement or is there another option?
![caputre](https://user-images.githubusercontent.com/30963205/84253448-509eb600-aae6-11ea-914a-8bb9b119cd2a.jpg)

Thank you.

**Comment by khamisEDX** [comment]
Having the same issue here any solutions ?

**Comment by robertoltrocha** [comment]
Hi,
Unfortunately not yet.

**Comment by letsar** [comment]
Can you try to remove the IconSlideAction from the widget tree?

**Comment by robertoltrocha** [comment]
Hi,
I haven't tried it and I don't know how to do it. I'll search. I don't want to remove all IconSlideAction (), just one when it doesn't meet a condition.
Example: if you are not a master user, the option to edit does not appear

**Comment by letsar** [comment]
You can have a condition to not add it to the list of actions:
```
Slidable(
  startActionPane: const ActionPane(
    motion: ScrollMotion(),
    children: [
      if(isAdmin) // <== The condition
        SlidableAction(
          onPressed: doNothing,
          backgroundColor: Color(0xFFFE4A49),
          foregroundColor: Colors.white,
          icon: Icons.delete,
          label: 'Delete',
        ),
      SlidableAction(
        onPressed: doNothing,
        backgroundColor: Color(0xFF21B7CA),
        foregroundColor: Colors.white,
        icon: Icons.share,
        label: 'Share',
      ),
    ],
  ),

  child: const ListTile(title: Text('Slide me')),
),
```
