### ISSUE TITLE
Can't access slidable state in actions

### ISSUE THREAD

**Issue by magpiedigital** [letsar/flutter_slidable#146]
First off, thanks for this excellent project!

I use a dismissible action to slide to dismiss. However, I would also like to dismiss if the action is tapped. However, I cannot access the context or the state within the actions.

```
return Slidable(
      key: UniqueKey(),
      actionPane: SlidableDrawerActionPane(),
      actionExtentRatio: 0.2,
      dismissal: SlidableDismissal(
        child: SlidableDrawerDismissal(),
        dismissThresholds: <SlideActionType, double>{
          SlideActionType.primary: 0.3
        },
      ),
      actions: <Widget>[
        IconSlideAction(
          caption: 'Complete',
          color: Colors.grey,
          icon: Icons.check,
          onTap: () {
            Slidable.of(context).dismiss(); // state returns null
          },
        ),
      ],
      child: ...
    );
```

**Comment by miDeb** [comment]
Hi! The problem here is that you are using the context that gets passed to your build method. This context does not include the Slidable context yet. You can work around this by using the [Builder](https://api.flutter.dev/flutter/widgets/Builder-class.html) widget. You can then use the context that gets passed to its builder function.

**Comment by magpiedigital** [comment]
I mean it's better if the context just gets passed in onTap, which is why I made https://github.com/letsar/flutter_slidable/pull/147

**Comment by miDeb** [comment]
You're probably right, I just wanted to add a possible workaround :)

**Comment by magpiedigital** [comment]
Sorry realised that sounds rude - yours is a good suggestion also

**Comment by miDeb** [comment]
No problem. Also, I didn't perceive your comment as rude at all. Have a nice day!

**Comment by letsar** [comment]
For the moment you can use the solution provided by @miDeb . I'm going to refactor all the code and keep in mind to add context to onTap :+1:
