### ISSUE TITLE
Is there any way to make slide action swipe more smooth?

### ISSUE THREAD

**Issue by Arun1811** [letsar/flutter_slidable#149]

**Comment by letsar** [comment]
Can you add more precisions?

**Comment by normancarcamo** [comment]
Same thing here, it would be nice to have another curve there, for example, `fastThreshold` is nice to show the options, super easy, but when I try to hide the options I have to swipe completely the options to hide 'em.

**Comment by letsar** [comment]
There is now a closeThreshold on actionPane in the 1.0 version to do that I suppose.

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
