### ISSUE TITLE
SliderAction with Transparent appears with white background

### ISSUE THREAD

**Issue by scaraux** [letsar/flutter_slidable#154]
I am trying to specify a transparent Color for the `SliderAction` background. I tried specifying with `color` and `decoration` properties, but it shows a white/gray background.

```
 return SlideAction(
      color: Colors.transparent,
      child: SizedBox(
        height: 31.0,
        width: 31.0,
        child: Image.asset(...),
      ),
      onTap: ...,
    );
```

**Comment by letsar** [comment]
Did you try with the last version?

**Comment by scaraux** [comment]
> Did you try with the last version?

I just tried `flutter_slidable: ^0.5.7` and the issue is resolved. Thank you.
