### ISSUE TITLE
Toggle every slidable list items

### ISSUE THREAD

**Issue by Dekhnar** [letsar/flutter_slidable#155]
Hello,

I want to toggle every slidable items into `SlideActionType.secondary` when i'm long pressing one item of my list.
How can I do it?

Thanks.

**Comment by Dekhnar** [comment]
@letsar any news?

**Comment by letsar** [comment]
Tricky one. You'll have create some kind of controller paired with a `StatefulWidget` that you will put under each `Slidable`. That `StatefulWidget`'s state will have a method to toggle its `Slidable` ancestor, and you'll have to register this method to your controller in the initState (and unregister it in dispose). So that the controller will have access to all the methods and you'll just have to iterate through all the method to call them and do what you want.

**Comment by Dekhnar** [comment]
I will implement this, thanks.

**Comment by letsar** [comment]
Can I close this?

**Comment by kenNg1** [comment]
@Dekhnar - It's not pretty but here's a way you can trigger all of the open states:

```
import 'package:flutter/material.dart';
import 'package:flutter_slidable/flutter_slidable.dart';

class MyCardsPage extends StatefulWidget {
  @override
  _MyCardsPageState createState() => _MyCardsPageState();
}

class _MyCardsPageState extends State<MyCardsPage> {
  final List<MyCard> list = [
    MyCard('1'),
    MyCard('2'),
    MyCard('3')
  ];

  bool isEdit = false;

  void openAll() {
    setState(() {
      isEdit = !isEdit;
    });
  }

  final SlidableController slidableController = SlidableController();

  @override
  Widget build(BuildContext context) {
    if (isEdit && list.isEmpty) {
      setState(() {
        isEdit = false;
      });
    }
    return SafeArea(
      child: Scaffold(
        body: Container(
          margin: EdgeInsets.only(top: 5),
          padding: const EdgeInsets.symmetric(horizontal: 5),
          child: Column(
            children: [
              ListView.builder(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                itemBuilder: (context, index) {
                  var listItem = list[index];
                  return Slidable(
                    key: listItem.key,
                    controller: isEdit ? null : slidableController,
                    actionPane: SlidableDrawerActionPane(),
                    actionExtentRatio: 0.10,
                    child: Container(
                        color: Colors.white,
                        // Sets the height to zero, so that whole Widget does not rebuild (prevents triggering open animation on every element)
                        height: listItem.willDelete ? 0 : 50,
                        child: ListTile(
                          leading: Icon(Icons.credit_card),
                          title: Builder(builder: (context2) {
                            if (isEdit) {
                              // To prevent: setState() or markNeedsBuild() called during build.
                              Future.delayed(
                                  Duration.zero,
                                  () => Slidable.of(context2).open(
                                      actionType: SlideActionType.secondary));
                            }
                            return Text(listItem.title);
                          }),
                        )),
                    secondaryActions: <Widget>[
                      Builder(builder: (context2) {
                        return IconSlideAction(
                          icon: Icons.delete,
                          color: Colors.red,
                          onTap: () => setState(() {
                            listItem.willDelete = true;
                            // TODO - API CALL TO DELETE CARD (once undo disappears)
                          }),
                        );
                      }),
                    ],
                  );
                },
                itemCount: list.length,
              ),
              TextButton(
                  onPressed: () => print('Add card pressed'),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [Icon(Icons.add), Text('Add Card')],
                  ))
            ],
          ),
        ),
        appBar: AppBar(
            title: Text(
              'My Cards',
            ),
            actions: <Widget>[
              Padding(
                  padding: EdgeInsets.all(20.0),
                  child: GestureDetector(
                    onTap: () => openAll(),
                    child: Text(
                      isEdit ? 'Done' : 'Edit',
                    ),
                  )),
            ]),
      ),
    );
  }
}

class MyCard {
  MyCard(this.title);
  final String title;
  UniqueKey key = UniqueKey();
  bool willDelete = false;
}
```

**Comment by Dekhnar** [comment]
> Can I close this?

Yes you can.

**Comment by Dekhnar** [comment]
> @Dekhnar - It's not pretty but here's a way you can trigger all of the open states.
> 
> Behaviour:
> 
> * When edit mode is not pressed - only one ListTile can be open at any one time (I do this with slidableController if edit mode is not pressed).
> * When edit mode is pressed - all ListTiles open.
> 
> Challenges & Solutions:
> 
> * I need to trigger the open method during the build phase within Slidable. Hence, I need to delay the state from updating until the build phase is done, I achieved this by running Future.delayed by Duration Zero.
> * If you dismiss a tile when edit mode is on, you cannot remove it from the List otherwise the whole component will rebuild and animations will trigger for each tile. Hence, I made the height of the components zero instead of removing the element from the List.
> 
> I hope this helps.
> 
> ![Simulator Screen Shot - iPhone 11 - 2020-11-10 at 03 43 09](https://user-images.githubusercontent.com/25297786/98588660-03c64200-2307-11eb-8b33-21c5bd4dce93.png)
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:flutter_slidable/flutter_slidable.dart';
> 
> class MyCardsPage extends StatefulWidget {
>   @override
>   _MyCardsPageState createState() => _MyCardsPageState();
> }
> 
> class _MyCardsPageState extends State<MyCardsPage> {
>   final List<MyCard> list = [
>     MyCard('1'),
>     MyCard('2'),
>     MyCard('3')
>   ];
> 
>   bool isEdit = false;
> 
>   void openAll() {
>     setState(() {
>       isEdit = !isEdit;
>     });
>   }
> 
>   final SlidableController slidableController = SlidableController();
> 
>   @override
>   Widget build(BuildContext context) {
>     if (isEdit && list.isEmpty) {
>       setState(() {
>         isEdit = false;
>       });
>     }
>     return SafeArea(
>       child: Scaffold(
>         body: Container(
>           margin: EdgeInsets.only(top: 5),
>           padding: const EdgeInsets.symmetric(horizontal: 5),
>           child: Column(
>             children: [
>               ListView.builder(
>                 shrinkWrap: true,
>                 physics: const NeverScrollableScrollPhysics(),
>                 itemBuilder: (context, index) {
>                   var listItem = list[index];
>                   return Slidable(
>                     key: listItem.key,
>                     controller: isEdit ? null : slidableController,
>                     actionPane: SlidableDrawerActionPane(),
>                     actionExtentRatio: 0.10,
>                     child: Container(
>                         color: Colors.white,
>                         // Sets the height to zero, so that whole Widget does not rebuild (prevents triggering open animation on every element)
>                         height: listItem.willDelete ? 0 : 50,
>                         child: ListTile(
>                           leading: Icon(Icons.credit_card),
>                           title: Builder(builder: (context2) {
>                             if (isEdit) {
>                               // Opens each of the ListView children which have Slidable in their context.
>                               // Future.delayed is needed to prevent setState() or markNeedsBuild() being called during the build phase.                              
>                               Future.delayed(
>                                   Duration.zero,
>                                   () => Slidable.of(context2).open(
>                                       actionType: SlideActionType.secondary));
>                             }
>                             return Text(listItem.title);
>                           }),
>                         )),
>                     secondaryActions: <Widget>[
>                       Builder(builder: (context2) {
>                         return IconSlideAction(
>                           icon: Icons.delete,
>                           color: Colors.red,
>                           onTap: () => setState(() {
>                             listItem.willDelete = true;
>                             // TODO - API CALL TO DELETE CARD (once undo disappears)
>                           }),
>                         );
>                       }),
>                     ],
>                   );
>                 },
>                 itemCount: list.length,
>               ),
>               TextButton(
>                   onPressed: () => print('Add card pressed'),
>                   child: Row(
>                     mainAxisSize: MainAxisSize.min,
>                     mainAxisAlignment: MainAxisAlignment.center,
>                     children: [Icon(Icons.add), Text('Add Card')],
>                   ))
>             ],
>           ),
>         ),
>         appBar: AppBar(
>             title: Text(
>               'My Cards',
>             ),
>             actions: <Widget>[
>               Padding(
>                   padding: EdgeInsets.all(20.0),
>                   child: GestureDetector(
>                     onTap: () => openAll(),
>                     child: Text(
>                       isEdit ? 'Done' : 'Edit',
>                     ),
>                   )),
>             ]),
>       ),
>     );
>   }
> }
> 
> class MyCard {
>   MyCard(this.title);
>   final String title;
>   UniqueKey key = UniqueKey();
>   bool willDelete = false;
> }
> ```

Thank @kenNg1 for this solution, I've already mine, but I'll confront it with your :)

**Comment by kenNg1** [comment]
@Dekhnar  what's your solution?

**Comment by DungNgo96** [comment]
@Dekhnar Can you show me your solution?

@kenNg1 I tried your code. It works and triggers all of the open states. However, it prevents the slidable items to open from normal slide? Do you know how to solve it?

**Comment by jlnrrg** [comment]
@letsar 
is there a way to toggle the slidable/ get the current value if the slidable is opened?

I want to open my Slidable on a mouse right click and it works. But as there seems to be no toggle function available/ no state exposed, building a toogle is quite hard rn.

<details><summary>Example</summary>

```dart
Slidable(
      key: ValueKey(value.id.value),
      startActionPane: ActionPane(
        extentRatio: 1/ 3
        motion: const ScrollMotion(),
        children: [
          SlidableAction(
              backgroundColor: Constants.wonColorDefault,
              icon: const AppIcons.edit().toIcon(context),
              onPressed: (_) => onEdit?.call()),
          SlidableAction(
              backgroundColor: Constants.lostColorDefault,
              icon: const AppIcons.trash().toIcon(context),
              onPressed: (_) => onDelete?.call()),
        ],
      ),
      child: Builder(builder: (context) {
        return Listener(
            onPointerDown: (event) { 
              if (event.kind == PointerDeviceKind.mouse &&
                  event.buttons == kSecondaryMouseButton) {
                final slidable = Slidable.of(context);
                if (slidable?. ?? false) {                      // <--- HERE
                  slidable?.openStartActionPane();
                } else {
                  slidable?.close();
                }
              }
            },
            child: ListTile(title: Text('test'))
            );
      }),
    );
```
</details>

**Comment by jlnrrg** [comment]
I solved it by using the `actionPaneType`

```dart
final slidable = Slidable.of(context);
if (slidable?.actionPaneType.value == ActionPaneType.start) {
  await slidable?.close();
} else {
  await slidable?.openStartActionPane();
}
```
