### ISSUE TITLE
handleSlideIsOpenChanged doesn't work

### ISSUE THREAD

**Issue by proformance** [letsar/flutter_slidable#156]
Hi,

First of all, this is a great widget!

Unfortunately I cannot get SlidableController to trigger when the slide is opened or closed.

I also saw another post about the same issue:
_Originally posted by @Darren-FanDemand in https://github.com/letsar/flutter_slidable/issues/35#issuecomment-665745653_

**Comment by SoundConception** [comment]
Yes, can confirm `onSlideIsOpenChanged` function is not being called for `flutter_slidable 0.5.5`.

**Comment by MarsGoatz** [comment]
Is there an another way to check if the slidable is open or not? Other than using ```onSlideIsOpenChanged```.

**Comment by MarsGoatz** [comment]
```onSlideIsOpenChanged``` is being triggered if I provide ```onSlideAnimationChanged```. So for now as a workaround, I am providing a dummy ```onSlideAnimationChanged```.

**Comment by proformance** [comment]
Interesting, thanks a lot for sharing the workaround!

**Comment by Darren-FanDemand** [comment]
Thanks @MarsGoatz, this worked for me.
