### ISSUE TITLE
Icons are rendered strangely

### ISSUE THREAD

**Issue by dvaldivia** [letsar/flutter_slidable#16]
Hi, thanks for building this awesome Widget, it's really helpful.

I'm running into a small issue, when I open the options, the icon is streched in a weird way.
<img width="514" alt="screen shot 2018-07-28 at 8 19 57 pm" src="https://user-images.githubusercontent.com/18384552/43362619-c122b30c-92a3-11e8-87c5-44479f4d0d38.png">

**Comment by letsar** [comment]
It looks like they are too big. Can you paste here the code that renders the `Slidable` and the slide actions?
