### ISSUE TITLE
Possible to disable sliding but still allow programmatic control? 

### ISSUE THREAD

**Issue by AlexHartford** [letsar/flutter_slidable#163]
I have a bit of a strange use case where I actually just want to use this to display options, but not enable sliding to access them.  An example would be issuing a voice command to display options that are currently available.

Setting the `enabled` flag to `false` cuts off interaction completely. What I'm looking for is essentially a `slideEnabled` flag. I have tried to come up with a reasonable solution given the current API so I wanted to reach out and see if you or anyone has an idea on how to accomplish this.

**Comment by AlexHartford** [comment]
[This pull request](https://github.com/letsar/flutter_slidable/pull/141) solves the issue. For now, I am pulling from the fork, but this seems like something that could be merged.

**Comment by letsar** [comment]
Thanks for the pull request. I will take this into account for my refactoring.

**Comment by letsar** [comment]
Can you test it with the 1.0 version?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
