### ISSUE TITLE
Other list items hide options when another item is dismissed from option

### ISSUE THREAD

**Issue by AlexHartford** [letsar/flutter_slidable#164]
Hard to explain, so here's a gif.

![weird_dismiss](https://user-images.githubusercontent.com/28658524/91366688-4b820680-e7b9-11ea-80aa-5e5d8e775f8f.gif)

Getting an unanimated option closing behavior on list items that have the options open when another item has a dismiss option selected.  Any ideas on how to fix this?

I'm not doing anything special, but here's the gist:

```dart

SlidableDismissal(
  child: SlidableDrawerDismissal(
    key: UniqueKey(),
  ),
  dragDismissible: false,
  onDismissed: (_) => list.remove(element),
);

SlideAction(
  ...
  onTap: () => Slidable.of(context).dismiss(),
  ...
);
```

**Comment by letsar** [comment]
Oh, since the list is rebuilt, your Slidable widgets are also rebuilt :/. What key did you provide to Slidable?

**Comment by letsar** [comment]
No responses since more than 8 months. I'm closing this.
