### ISSUE TITLE
Animation inertia

### ISSUE THREAD

**Issue by dave** [letsar/flutter_slidable#165]
When I flick the slider open fast, as soon as my finger leaves the screen, the speed of the slider is reduced. Is there an easy way to add some inertia to the speed of the animation so it doesn't slow down when the swipe ends?

You can see the effect here:

https://photos.app.goo.gl/C2Y88shvDbPqZWzD8

**Comment by letsar** [comment]
I saw the video, but I don't understand the problem. Can you elaborate?

**Comment by danhardman** [comment]
@letsar When swiping, if you do a "quick" swipe and release, the animation kicks in and slowly completes the last part of the swipe.

E.g. [0 ---20------- 100]

You do a fast swipe on that aiming from 100% to 0% , this library stops the swipe at 20% and performs a slow, smooth animation to complete the last bit. This makes it look "jerky" 

Apologies I haven't jumped in to take a look at what's going on but hopefully this explains the issue enough to you and is what @dave  also experienced

**Comment by dave** [comment]
Yes that's exactly the experience I had...

**Comment by danhardman** [comment]
Hi @letsar Does this explain the issue well enough? Is this something that's likely to be looked at or would you be happy to accept a PR? It'd be good to get an idea of where you think the issue lies if you cannot work on it yourself :)

**Comment by letsar** [comment]
Can you test your use case with the 1.0 version?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
