### ISSUE TITLE
Not able to open slidable programmatically

### ISSUE THREAD

**Issue by shanazainab** [letsar/flutter_slidable#171]
Unhandled Exception: NoSuchMethodError: The method 'open' was called on null.
E/flutter (10705): Receiver: null
E/flutter (10705): Tried calling: open(actionType: Instance of 'SlideActionType')

**Comment by Leomhl** [comment]
I have the same issue! 

The method 'open' was called on null.
Receiver: null
Tried calling: open()

I'm using Slidable.of(context).open(); inside a Gesture Detector.


 return Slidable(  
      actionPane: SlidableDrawerActionPane(),
      controller: _slidableController,
      actionExtentRatio: 0.25,
      
      child: GestureDetector(
      onTap: () {
        Slidable.of(context).open();
      }, ...



When I try to use SlidableState().open() I receive the error:



════════ Exception caught by gesture ═══════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'controller' was called on null.
Receiver: null
Tried calling: controller

**Comment by Leomhl** [comment]
I solve the problem using this code:


    final _slidableKey = GlobalKey<SlidableState>();

    return Slidable(  
      actionPane: SlidableDrawerActionPane(),
      key: _slidableKey,
      actionExtentRatio: 0.25,
      
      child: GestureDetector(
      onTap: () {
        _slidableKey.currentState.open(
          actionType: SlideActionType.secondary,
        );
      },

**Comment by shanazainab** [comment]
Great! Thank you it worked !!

**Comment by jialin97** [comment]
Is the ```SlidableState``` deprecated?
