### ISSUE TITLE
Slidable child flowing outside of parent container

### ISSUE THREAD

**Issue by urmilshroff** [letsar/flutter_slidable#174]
If a `Slidable()` is wrapped inside a `Container()` with fixed width, the `child` of the `Slidable()` still flows outside of the `Container()` when swiped to display actions.

Here is my example:
```
Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey, // to differentiate background for demo
      body: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                // should create a limited area for Slidable to work in
                width: 500.0,
                child: Slidable(
                  actionPane: SlidableStrechActionPane(),
                  actionExtentRatio: 0.25,
                  child: Container(
                    // BUG: child slides out of Container
                    color: Colors.white,
                    child: ListTile(
                      leading: CircleAvatar(
                        backgroundColor: Colors.indigoAccent,
                        child: Text('3'),
                        foregroundColor: Colors.white,
                      ),
                      title: Text('Tile n°3'),
                      subtitle: Text('SlidableDrawerDelegate'),
                    ),
                  ),
                  actions: <Widget>[
                    IconSlideAction(
                      caption: 'Archive',
                      color: Colors.blue,
                      icon: Icons.archive,
                    ),
                    IconSlideAction(
                      caption: 'Share',
                      color: Colors.indigo,
                      icon: Icons.share,
                    ),
                  ],
                  secondaryActions: <Widget>[
                    IconSlideAction(
                      caption: 'More',
                      color: Colors.black45,
                      icon: Icons.more_horiz,
                    ),
                    IconSlideAction(
                      caption: 'Delete',
                      color: Colors.red,
                      icon: Icons.delete,
                    ),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
```
![Screenshot on 2020-10-31 at 11 28 00 AM](https://user-images.githubusercontent.com/8844095/97772437-1f925100-1b6d-11eb-8111-c1ed52db78f6.gif)

Is this a bug or intended behavior? If so, how can I limit the `child` to display only in a constrained container? Thanks in advance.

**Comment by sbrsubuvga** [comment]
I also faced similar issue,
but it only happens when parent widget is not scrollable.

**Comment by letsar** [comment]
Yeah I think it need to be clipped. You can probably do it from your side, but I should do it in Slidable.
I will work on this on december.

**Comment by clement89** [comment]
I am also getting the same issue.

**Comment by clement89** [comment]
@letsar Can you provide a sample code to clip the widget.?

**Comment by sbrsubuvga** [comment]
> Yeah I think it need to be clipped. You can probably do it from your side, but I should do it in Slidable.
> I will work on this on december.
 Can you provide a sample code to clip the widget.?

**Comment by IronforgeAsh** [comment]
Any update on this?

I have this problem, and im not sure how to fix it.

**Comment by clement89** [comment]
@IronforgeAsh I dix this issue by adding Slidable inside ClipRect widget.

**Comment by mattbreeland** [comment]
Thanks very much @clement89 ! I had problems where sliding out cards within a PageView, then switching PageViews, would show a card from the previous page on the next one. This fixes it up nicely.

**Comment by sbrsubuvga** [comment]
> @letsar Can you provide a sample code to clip the widget.?

```
ClipRect(
  child: Slidable(
  
  ),
)
```
 Fixed this issue by adding Slidable inside ClipRect widget.

**Comment by ianvillamia** [comment]
> 
> 
> @IronforgeAsh I fix this issue by adding Slidable inside ClipRect widget.

Thanks ! this works

**Comment by letsar** [comment]
Should be ok with 1.0.

**Comment by vsilux** [comment]
@letsar Hi, is it possible to disable clipping?)
