### ISSUE TITLE
How to cancel onTap on Slideable to open Slide Action

### ISSUE THREAD

**Issue by freedemocracy** [letsar/flutter_slidable#177]
How to cancel onTap event in Slidable。

onTap has other functions

thank you！

**Comment by freedemocracy** [comment]
I don’t want to click on Slidable, just open the action panel

**Comment by letsar** [comment]
I don't understant what you want, can you explain?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
