### ISSUE TITLE
[BUG] when using open() animation not working

### ISSUE THREAD

**Issue by shovelmn12** [letsar/flutter_slidable#179]
When using `open(actionType: SlideActionType.secondary)` and afterwards trying to slide back, horizontal drag, to close the widget just jumps back to closed state instead of animating back. after that every time I try to slide to open/close it just skips the animation and jumps to open or close with no animation.

code being used to open the slidable:
```
 GestureDetector(
        onTap: () => Slidable.of(context).open(
          actionType: SlideActionType.secondary,
        ),
        child: Icon(Icons.more_vert),
      )
```

slidable config:
```
       actionPane: const SlidableDrawerActionPane(),
       actionExtentRatio: .25,
       child: SomeWidget()
       secondaryActions: [ ...some actions ],
       // actions: not set as i only need actions from the right, is RTL ill probably need from left
```

**Comment by letsar** [comment]
Can you test it with 1.0 version?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
