### ISSUE TITLE
How to let keep only one Slidable open?

### ISSUE THREAD

**Issue by Paolo9711** [letsar/flutter_slidable#182]
In the documentation it is explained that it is needed "to set the controller parameter of the Slidable constructors to a SlidableController instance" to do this, but I tried it and it doesn't work.

**Comment by alexandrelc16** [comment]
@Paolo9711 I had the same problem and resolve using stateful widget.

**Comment by Paolo9711** [comment]
@alexandrelc16 I have already tried with stateful widget, but it still doesn't work. Can you please provide a sample code?

**Comment by alexandrelc16** [comment]
@Paolo9711 sample code with version ^0.5.7:

`class TestList extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _TestListState();
}

class _TestListState extends State<TestList> {
  final SlidableController _slidableController = SlidableController();

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: 20,
      itemBuilder: (BuildContext context, int index) => Slidable(
        actionPane: const SlidableDrawerActionPane(),
        key: Key('key ${index.toString()}'),
        controller: _slidableController,
        child: ListTile(title: Text('Title ${index.toString()}')),
        secondaryActions: [
          IconSlideAction(
            caption: 'Delete',
            icon: Icons.delete,
          ),
        ],
      ),
    );
  }
}`

**Comment by Paolo9711** [comment]
@alexandrelc16 Thank you for the fast response. Unfortunately I applied exactly the same criteria to my project but it still doesn't work.
