### ISSUE TITLE
Animated delete

### ISSUE THREAD

**Issue by lironiz** [letsar/flutter_slidable#184]
I would like my slidable item to be deleted when the user clicks on the IconSlideAction, and I want it to be animated, so that the slide action would continue and the original direction. how do I achieve this?

**Comment by mjablecnik** [comment]
For this purpose you can try ImplicitlyAnimatedList from https://pub.dev/packages/implicitly_animated_reorderable_list

**Comment by letsar** [comment]
You can now do it in the latest 1.0 version (https://github.com/letsar/flutter_slidable/issues/31#issuecomment-880840889)
