### ISSUE TITLE
Slidable within TabBar

### ISSUE THREAD

**Issue by marcoberetta96** [letsar/flutter_slidable#185]
Hi!
I have a TabBar with two Tabs.
In the right Tab I have a ListView and I need each element to be a Slidable with a secondaryAction.
When I set the secondaryActions, I cannot anymore swipe back to the first tab.
I really need to be able to perform this and I think it's possible since the swipes are in opposite directions.
How can I do this?
Thanks!

**Comment by jkevingutierrez** [comment]
Same thing with a BottomNavigationBar.

It would be great that if I only define secondaryActions and the action is not visible, the right drag of the BottomNavigationBar or the TabBar or any Gesture defined by the parent should still work.

Or if only define a PrimaryAction and the widget of the actions is not visible, the left drag should still work for parent elements.

**Comment by pratikbaid3** [comment]
If we could have an option to disable swipe in one particular direction, I guess that would solve the roblem

**Comment by MishalPatel** [comment]
Hello 
I have a using two tab bar but using slidable pageview scroll is not working.
Please provide me a proper solution.

**Comment by AnubhavPrasad** [comment]
Yes i really want this feature of disabling swipe in one direction so that it can be implemented easily with tabviews.

**Comment by marcoberetta96** [comment]
Any update on this?

**Comment by letsar** [comment]
I don't think having two widgets that can scroll in the same direction is not a good idea. There have been similar requests in the past, but I won't work on this. PR are welcome though.
