### ISSUE TITLE
Position Issue

### ISSUE THREAD

**Issue by saleh-aleid** [letsar/flutter_slidable#188]
<img width="1123" alt="Screen Shot 2020-12-10 at 2 48 05 PM" src="https://user-images.githubusercontent.com/11992777/101768701-f44d3b00-3af6-11eb-8146-d6382f36312b.png">

**Comment by saleh-aleid** [comment]
@letsar dear 

this problem come if i use tablet

**Comment by letsar** [comment]
Hi @saleh-aleid , the upcoming version will fix that but I need to gather enough feedback before publishing it.
You can test it on the feature/revival branch.

**Comment by NewSystem02** [comment]
@saleh-aleid Sometimes happen to me too only on tablet

**Comment by saleh-aleid** [comment]
@letsar feature/revival branch is is working fine but not support null safety.

**Comment by letsar** [comment]
Yes I need to work on it

**Comment by saleh-aleid** [comment]
@letsar which time you will release it

**Comment by letsar** [comment]
Can you test it with the 1.0 version? It's fixed now.
