### ISSUE TITLE
Slidable widget exponentially lags entire application until it crashes

### ISSUE THREAD

**Issue by velcz** [letsar/flutter_slidable#189]
I'm very confused what exactly is causing this issue as I haven't read about anyone else encountering it, but I DID figure out where the issue was coming from and figured out a temporary solution.

As the title says, after installing this plugin and trying to implement it, attempting to drag the slidable would work as intended for a few seconds, until exponentially slowing down, lagging the entire app, then ultimately completely freezing.

I figured out that the issue's roots are in the `_initAnimations() `method of `SlidableState`, specifically when it is called under `set actionType`. I put a print command inside the setter to see that it is being called hundreds of times every second when the slidable widget is dragged, rapidly calling `_initAnimations()`, and as a result creating and destroying hundreds of status listeners.

This issue made the plugin completely unusable, but I fixed the issue by changing the `set actionType` to only call `_initAnimations()` if the `SlideActionType` was changed, like so:
```
 SlideActionType _previousType;
  set actionType(SlideActionType value) {
    _actionType = value;
    if (_actionType != _previousType) {
      _initAnimations();
      _previousType = _actionType;
    }
  }
```
I'm on the master channel of flutter, I assume something new they changed about the framework may have caused something in the plugin to go haywire. Here's my versions from flutter doctor:
```
[√] Flutter (Channel master, 1.26.0-18.0.pre.212, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.53.0)
[√] Connected device (3 available)
```

**Comment by devwerewolf** [comment]
Bump. Thank you for the quick fix! Knew something wasn't right.

When you implement this workaround, make sure to place a question mark (`?`) to make `_previousType` nullable. Like this:

```dart
SlideActionType? _previousType; // <-- Hush the debugger errors
  
set actionType(SlideActionType? value) {
  _actionType = value;
  
  if (_actionType != _previousType) {
    _initAnimations();
    _previousType = _actionType;
  }
}
```

My app is saved! 🎉
