### ISSUE TITLE
dismiss on button tap

### ISSUE THREAD

**Issue by CedSW** [letsar/flutter_slidable#19]
Hi is it possible to dismiss row on button tap?
I would like to display confirmation dialog first and if user hit ok, dismiss the row.
Thank you!

**Comment by letsar** [comment]
Oh I succeeded to do what you want by getting the state before showing the `AlertDialog`.
The code below is what I put in the `tap` callback of my slide action:
``` dart
onTap: () async {
                  var state = Slidable
                      .of(context);
                  var dismiss = await showDialog<bool>(
                    context: context,
                    builder: (context) {
                      return new AlertDialog(
                        title: new Text('Delete'),
                        content: new Text('Item will be deleted'),
                        actions: <Widget>[
                          new FlatButton(
                            child: new Text('Cancel'),
                            onPressed: () => Navigator.of(context).pop(false),
                          ),
                          new FlatButton(
                            child: new Text('Ok'),
                            onPressed: () => Navigator.of(context).pop(true),
                          ),
                        ],
                      );
                    },
                  );

                  if (dismiss) {
                    state.dismiss();
                  }
                },
```

**Comment by CedSW** [comment]
thank you for you reply, but unfortunately I didn't manage to reproduce your solution.
Error is: NoSuchMethodError: The method 'dismiss' was called on null. I manage to come up with workaround using streams, but I still wonder where is the problem :/

here is my code

`secondaryActions: <Widget>[
        SlideAction(
          onTap: () async {
            var state = Slidable
                .of(context);
            var dismiss = await showDialog<bool>(
              context: context,
              builder: (context) {
                return AlertDialog(
                  title: Text(S.of(context).confirmDeletion),
                  content: Text(S.of(context).deletionDescription),
                  actions: <Widget>[
                    FlatButton(
                      child: Text(S.of(context).cancel),
                      onPressed: () => Navigator.of(context).pop(false),
                    ),
                    FlatButton(
                      child: Text(S.of(context).ok),
                      onPressed: () =>  Navigator.of(context).pop(true),
                    )
                  ],
                );
              },
            );

            if (dismiss) {
              state.dismiss();
            }
          },
          color: _tag.color,
          child: Icon(Icons.delete, color: Colors.white,),
        )
      ],`

**Comment by letsar** [comment]
I forgot to mention you should use the `Slidable.builder` constructor and `SlideActionBuilderDelegate`s, otherwise you will end up with the same context as the `Slidable`. This is why `Slidable.of(context)` is `null`.

**Comment by fullflash** [comment]
> I forgot to mention you should use the `Slidable.builder` constructor and `SlideActionBuilderDelegate`s, otherwise you will end up with the same context as the `Slidable`. This is why `Slidable.of(context)` is `null`.

there is no examples with SlideActionBuilderDelegates and Slidable.builder.
