### ISSUE TITLE
Request for rounded corner when slide. 

### ISSUE THREAD

**Issue by pavel-birdy** [letsar/flutter_slidable#194]
Here is an example of the google Gmail app (android) if you try to slide the tile corner will become rounded. I think also have some shadow. 

![photo_2021-03-12 19 49 49](https://user-images.githubusercontent.com/53362329/110952576-68a0b000-836c-11eb-8ff1-102b1571a7b9.jpeg)

Here another example of Telegram android app which also has rounded corners when slides

![photo_2021-03-12 19 49 45](https://user-images.githubusercontent.com/53362329/110952803-a43b7a00-836c-11eb-9ec3-e0dceb4f373b.jpeg)

**Comment by selvas1998** [comment]
The problem is card's deafult margin is 4.0, so you have to reduce the size to make compatible to slidable widget.
**Solution:**
You can achieve by setting Card margin right as 0.0.
Slidable(
child: Card(
 margin: EdgeInsets.only(right: 0.0)
child: ......
))

**Comment by rachet-khanal** [comment]
This helped me to make similar rounded corners effect: [Issue 173](https://github.com/letsar/flutter_slidable/issues/173#issuecomment-742760829)

**Comment by pavel-birdy** [comment]
I published this package which solved my issue. https://pub.dev/packages/swipeable_tile
