### ISSUE TITLE
IconSlideAction caption TextStyle?

### ISSUE THREAD

**Issue by NTMS2017** [letsar/flutter_slidable#197]
Hi,

I need to change IconSlideAction caption TextStyle, how do I do that?

The caption text size is different in iPhone SE 1. edition, iPhone 11 and iPad mini 4. 

Thanks

**Comment by letsar** [comment]
You can use any widget you want instead of the built in actions. There are only here for convenience, but if they don't fit your needs you can use your own specialized widgets.
