### ISSUE TITLE
Keep slide opened after rebuilding

### ISSUE THREAD

**Issue by Herrera93** [letsar/flutter_slidable#199]
I have a sliver list that gets rebuild after receiving an event from a stream, is there a way I can keep the slide opened after rebuild the list ?

**Comment by alvincast** [comment]
did u figure out how to solve it?

**Comment by Herrera93** [comment]
@alvincast no, still waiting for a solution

**Comment by letsar** [comment]
Can you test with the 1.0 version? It should be fixed.

**Comment by Herrera93** [comment]
Yes, its working now
