### ISSUE TITLE
Vertical

### ISSUE THREAD

**Issue by Solido** [letsar/flutter_slidable#2]
I guess one word is enough to describe the idea ;)
This is not a requirement but better have it in mind since designers will come with it one day or another.

**Comment by letsar** [comment]
For now we can slide to the left or to the right, and if I understand, this feature would be to allow the item to slide to the top or to the bottom?
If it's the case, it would interfere with the scroll, wouldn't it?

**Comment by Solido** [comment]
This library is based on the concept of dismissible which mainly is found on vertical list.

You slide horizontal when the List is vertical
You may have to slide vertical when the list is horizontal aka PageView

Imagine a PageView of Images, you can slide UP to display more control items under the bottom of image. Since it's horizontal you can have more options.

**Comment by letsar** [comment]
Available on version 0.2.0
