### ISSUE TITLE
Show actions vertically

### ISSUE THREAD

**Issue by Inassdev** [letsar/flutter_slidable#208]
is there is a way to change Axis of actions button to shown vertically , button under button, 
<img width="446" alt="Capture d’écran 2021-04-27 à 10 12 26" src="https://user-images.githubusercontent.com/17359618/116225535-7e620d00-a741-11eb-9aa7-02ed92a98de3.png">

**Comment by letsar** [comment]
You can use any widget as an action, so you can do it in your app
