### ISSUE TITLE
Don't know the index of the item is sliding

### ISSUE THREAD

**Issue by CuongNV12** [letsar/flutter_slidable#218]
I am having:
```
_slidableController = SlidableController(
      onSlideAnimationChanged: handleSlideAnimationChanged,
      onSlideIsOpenChanged: handleSlideIsOpenChanged,
    );
```
```
  void handleSlideIsOpenChanged(bool? isOpen) {
  }
```
The isOpen variable provides no specific index, i need specific index of sliding item to perform some action like change the color of current sliding item...

Please help!

**Comment by Vanessa-Berazategui** [comment]
Hi all, I have the same question, I need to change the size of the item I'm sliding. How can I could get it?

I saw that i could do something like this:

` void _handleSlideIsOpenChanged(bool isOpen) {
    if (isOpen) {
      ValueKey key = slidableController.activeState.widget.key;
      _bloc.setOpenedSlide(isOpen, int.parse(key.value));
    } else {
      _bloc.setOpenedSlide(false, -1);
    }
  }
  }`
  
  but when you also slide another item and you have  closeOnScroll: true, this method is not invoked so I can't update the new item slided.

Thank you.

**Comment by letsar** [comment]
This is not the purpose of this package. You can however pass this information using an InheritedWidget, Provider, Binder, or any other state management solution.
If you can to change the color of the current sliding item you can however get the SlidableController in the Slidable's child and listen to the ratio, or action pane type.
I made a comment for doing something like this: https://github.com/letsar/flutter_slidable/issues/167#issuecomment-884697665
