### ISSUE TITLE
v0.6.0 Flutter integration testing - 6-28 second delay when opening drawer 

### ISSUE THREAD

**Issue by dm-ra-01** [letsar/flutter_slidable#220]
I've been troubleshooting this for a few days now without success. 
I can open the drawer no problem, however I have to wait 6-7 seconds for the tree/variables to rebuild. 

I set a breakpoint in VS Code and could see a circular progress until it reloads the state a long time later. 
This is slowing down my integration tests quite significantly so I would appreciate any advice. 

Does this drawer opening action force a complete rebuild of the app?? I can't seem to find a suitable explanation for the delay. 

I've tried multiple options below which are all successful, however delayed by 6-7 seconds on iOS and 20-28 seconds on Android

  flutter_slidable: ^0.6.0

### Option 1
  Future<void> swipeRight(Finder finder) async {
    await tester.drag(finder, const Offset(300, 0));
    await tester.pump();
  }

### Option 2
  Future<void> swipeRight(Finder finder) async {
     await tester.timedDrag(
      finder, const Offset(300, 0), const Duration(milliseconds: 50));
  }

### Option 3
 final _slidableContext = tester.element(find.descendant(
          of: finder,
          matching: find.byType(SlidableDrawerActionPane)));
      Slidable.of(_slidableContext).open();

  await tester.pump(const Duration(milliseconds: 300));

This is with both iOS and android simulators

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.2.3 20D91 darwin-arm, locale en-AU)
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

**Comment by letsar** [comment]
Can you test it with the 1.0 prerelease?

**Comment by dm-ra-01** [comment]
Tested with 1.0 pre-release   flutter_slidable: ^1.0.0-dev.2
 I still have the same issue

Also, icons are larger than original, in case you weren't aware. I understand it's a dev build. 
<img width="87" alt="Screen Shot 2021-07-04 at 3 44 33 pm" src="https://user-images.githubusercontent.com/58808693/124374472-d63b6800-dcde-11eb-87c5-68db9876caff.png">
<img width="88" alt="Screen Shot 2021-07-04 at 3 44 37 pm" src="https://user-images.githubusercontent.com/58808693/124374473-d8052b80-dcde-11eb-83c9-922606028388.png">

**Comment by dm-ra-01** [comment]
I tested the same problem with a different area of my app and found it worked perfectly. I'll investigate the differences between the two ares of the app and I'll let you know what I find.

**Comment by dm-ra-01** [comment]
Romain I'm going to close this issue until I found something reproducible and valuable to your work. It now works on two of three modules using flutter_slidable.
