### ISSUE TITLE
[Request] make Font-size on SlidableAction's Label  settable, and instead of having an icon property, make it a Widget (flutter_slidable 1.0.0-dev.2)

### ISSUE THREAD

**Issue by pmi-ava** [letsar/flutter_slidable#221]
currently there is no way to set Font-size for SlidableAction's Label, and most of my labels go in Overflow.
It would be good to being able to pass a "Text()" widget here.

Also for SlidableAction's icon property, this should be changed from type "IconData", to at least Icon() or even better, a Widget(), in this way we can pass our custom Icons (like an Icon wrapped by a container for some specific effects)

**Comment by pmi-ava** [comment]
EDIT: I see that we can instead of using a SlidableAction's, we could pass our own Flexible widget

**Comment by Albertbol** [comment]
Or CustomSlidableAction
