### ISSUE TITLE
`close()` not being called when manually swiping actions closed

### ISSUE THREAD

**Issue by lane-faison** [letsar/flutter_slidable#222]
**Steps to reproduce**
1. Have a tile that has a tap action for it, such as opening a message.
2. Hold down on the tile and swipe right-to-left to reveal secondary actions.
3. Without removing your finger, swipe left-to-right to hide the secondary actions.
4. Remove your finger and tap on the tile.

**Expected result**
- Tap action on tile is called

**Actual result**
- Tap action on tile is **not** called because the **Slidable** widget is still considered active.

**Comment by letsar** [comment]
@lane-faison what is the version of Slidable you use? Does it still happen in the 1.0 prerelease: https://pub.dev/packages/flutter_slidable/versions/1.0.0-dev.2?

**Comment by lane-faison** [comment]
@letsar Our app is still on Flutter 1.22.6 so we haven't been able to update to 0.6.0 or later. Is this issue resolved on the prerelease?

**Comment by lane-faison** [comment]
@letsar Can you point me to the commit where this was fixed? We may need to fork this package in order to fix it.

**Comment by letsar** [comment]
Hi @lane-faison, I completely rewritten the package in the 1.0 version, so if it's resolved in 1.0, you would have to fork the 1.0 version in order to make it compatible with your version of Flutter.

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
