### ISSUE TITLE
Sometime i get null exception

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [letsar/flutter_slidable#223]
Hi,

sometimes i see this error in errors log but not sure how to catch it:

```
_CastError: Null check operator used on a null value
  File "framework.dart", line 916, in State.context
  File "slidable.dart", line 882, in SlidableState._startResizeAnimation.<fn>
  File "framework.dart", line 1088, in State.setState
  File "slidable.dart", line 880, in SlidableState._startResizeAnimation
  File "slidable.dart", line 844, in SlidableState._handleDismissStatusChanged
```

**Comment by letsar** [comment]
What version of flutter_slidable do you use? If it's under 1.0, the code has been rewritten and it would be better to use the 1.0 version.

**Comment by vytautas-pranskunas-** [comment]
Flutter version: 2.2.3
flutter_slidable: ^0.6.0

This error is not common. But happens sometimes sepcially when interaction is not so smooth like starting dragging when another drag is not finished or some other haotic user bahaviour applies. 
Also, during this haotic user interaction, sometimes i get another error saying that widget is still part of the widget tree.

**Comment by letsar** [comment]
Can you try with the 1.0 version?

**Comment by vytautas-pranskunas-** [comment]
I will, have you fixed something?

**Comment by letsar** [comment]
Yes, it's a complete refactoring with a lot of unit tests, so I hope a lot of issues are now resolved.

**Comment by vytautas-pranskunas-** [comment]
OK, I will add it.
Hopefully there were no API changes and it will not start crashing :) I am bit scared of bug refactorings but hopefully they are for good! ;)

**Comment by vytautas-pranskunas-** [comment]
@letsar but 1.0.0 is not yet available. It is in dev phase.

**Comment by letsar** [comment]
It's available in preview yes, but you can already use it: flutter_slidable: ^1.0.0-dev.6

**Comment by vytautas-pranskunas-** [comment]
do you think it is stable enough?

**Comment by letsar** [comment]
Yes, I will soon release it as stable 1.0.0, if there aren't any other issues.

**Comment by vytautas-pranskunas-** [comment]
fastThreshold - is gone and there is no metnion in migration guide: https://github.com/letsar/flutter_slidable/wiki/Migration-from-version-0.6.0-to-version-1.0.0

**Comment by vytautas-pranskunas-** [comment]
Also there is not mention about ```controller``` which was in 0.6

**Comment by vytautas-pranskunas-** [comment]
```fastThreshold``` without it dismiss treshold is not respected.
If I move dismissable widget slowly but less then 0.75 width dismiss treshhold is respected, however if i try to move it realy quick but just 0.2 it is enought for widget to get dismissed


https://user-images.githubusercontent.com/3918999/126667120-a4c2898f-6c59-4a24-b918-ef7ad3ad2614.mov

**Comment by letsar** [comment]
Closing since it's not the same issue.
