### ISSUE TITLE
Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 771 pos 7: '_ticker != null': AnimationController.stop() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by amed901107** [letsar/flutter_slidable#231]
it throws this exception the 2nd time I swipe to the left fully and lift a SlidingUpPanel

**Comment by letsar** [comment]
Can you try with the 1.0.0-dev.8 version?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
