### ISSUE TITLE
Option to change label textstyle

### ISSUE THREAD

**Issue by DogeeeXD** [letsar/flutter_slidable#232]
Is there an option to change label textstyle?
I'm using flutter_slidable: ^1.0.0-dev.8

**Comment by letsar** [comment]
I don't want these widgets to be too complex, that's why I didn't add all the properties to customize them.
But you can set the style by wrapping the action with a `DefaultTextStyle` if you want.

**Comment by DogeeeXD** [comment]
I tried to wrap one of the SlidableAction this way, but it doesn't work. The text fontSize is not changed. 
 ```
DefaultTextStyle(
                              style: TextStyle(fontSize: 12),
                              child: SlidableAction(
                                backgroundColor: Colors.grey,
                                foregroundColor: Colors.white,
                                flex: 1,
                                icon: chatRoom.isMuted
                                    ? Icons.volume_up_rounded
                                    : Icons.volume_off,
                                label: chatRoom.isMuted ? 'Unmute' : 'Mute',
                                onPressed: (context) {},
                              ),
                            ),
```

**Comment by letsar** [comment]
Oh my bad, `SlidableAction` uses an `OutlinedButton`, so either you define your own action (which can be any widget, `SlidableAction` only exists to speed up the common process) so that you can do what you want. Or you instead of wrapping it with `DefaultTextStyle`, you wrap it with `OutlinedButtonTheme`:
``` dart
OutlinedButtonTheme(
  data: OutlinedButtonThemeData(
    style: ButtonStyle(
      textStyle: MaterialStateProperty.all(TextStyle(fontSize: 24)),
    ),
  ),
  child: SlidableAction(...),
),
```
