### ISSUE TITLE
[1.0.0 Feature Request] SlidableController & onSlide in v1.0.0

### ISSUE THREAD

**Issue by DogeeeXD** [letsar/flutter_slidable#233]
I've been using v0.6.0 with the SlidableController to close the slide through other actions.
Is there a controller in v1.0.0? If no is it possible to add it in?

Also, is it possible to make just only one slidable active at once? Like implementing a onSlide function to use.
So I can call something like this in the onSlide function.
```
 if (slidableController.activeState != null) {
      slidableController.activeState.close();
    }
```
EX: I have 3 Slidable with ListTile as child, when I slide open the first one, then go ahead to slide the second one, the first one should close automatically.

Thank you for the good package.

**Comment by letsar** [comment]
Yes you can do it. It seems this is something I did not document in the readme or the migration guide, sorry for that.
You can look to this example to see how to make it work: https://github.com/letsar/flutter_slidable/blob/master/example/lib/main_demo.dart#L46

Simply wrap your list with `SlidableNotificationListener`, and it should be good. You can also have different groups if you set different `groupTag` to your Slidables.

**Comment by DogeeeXD** [comment]
Thank you for the info, it works perfectly!
