### ISSUE TITLE
RTL not support

### ISSUE THREAD

**Issue by m2faridi** [letsar/flutter_slidable#238]
pls fix this bug in version
flutter_slidable: ^1.0.0-dev.9

**Comment by letsar** [comment]
Can you explain what you want exactly? start/end action panes are defined from ambient TextDirection

**Comment by m2faridi** [comment]
Items are not displayed
Instead of swiping from left to right, swipe from right to left, and there are no items to display because the items are actually on the left, but the library for fonts is not the opposite.

**Comment by m2faridi** [comment]
fix bugs 
`useTextDirection: false`
