### ISSUE TITLE
Child shifted up when sliding

### ISSUE THREAD

**Issue by fregate** [letsar/flutter_slidable#240]
Hi
If I slide item it's shifting up
![Screenshot from 2021-08-10 20-08-03](https://user-images.githubusercontent.com/4081464/128967129-80b67237-0adc-4fc5-8d28-372aef39a4ea.png)
![Screenshot from 2021-08-10 20-08-20](https://user-images.githubusercontent.com/4081464/128967132-163d4b43-a97a-4f67-8398-31a8d0195b11.png)

If I wrap child content with Center() - everything ok.
Version 0.6.0

**Comment by letsar** [comment]
Hi I won't maintain the 0.6 version anymore, does it happen also in the 1.0 ?

**Comment by fregate** [comment]
Now I can't check it on newer version because of legacy code (non-null isn't supported yet).
So I've wrapped this with center() and it's ok for now
