### ISSUE TITLE
Automatically closes the last open item on the list

### ISSUE THREAD

**Issue by jingzhanwu** [letsar/flutter_slidable#242]
How do you set the opening of a new item in the list to automatically close the previous item

**Comment by golanir** [comment]
would like to know that too, worked good on 0.6.0 but not working on 1.0.0-dev.9

**Comment by duykhanhhs1** [comment]
the same question

**Comment by golanir** [comment]
@jingzhanwu found it, wrap your list with SlidableNotificationListener, that will fix the issue

**Comment by letsar** [comment]
This documentation is in the [FAQ](https://github.com/letsar/flutter_slidable/wiki/FAQ#how-to-keep-only-one-slidable-open) now.
