### ISSUE TITLE
Don't support RTL

### ISSUE THREAD

**Issue by KalaliEhsan** [letsar/flutter_slidable#244]
How to implement flutter_slidable directionality by support **RTL**?

**Comment by letsar** [comment]
Slidable supports RTL, can you provide more information and an example please?

**Comment by dryasbk** [comment]
After update to flutter_slidable 1.1.0 
If I add only startActionPane , no Color nor Icon seen. 
even if I add only endActionPane.

tried to add both and make one of them without action I could not.

in your example main_outside_list.dart

I tried it in 1st slidable gave same error
but in 2nd slidable it worked ok

I changed the 
Directionality(
              textDirection: TextDirection.rtl,
to :
Directionality(
              textDirection: TextDirection.ltr,

it work as it should be

**Comment by letsar** [comment]
Thanks for this issue I didn't test with only one action pane. Can you test with the master branch?

**Comment by dryasbk** [comment]
I tried again. this the result
and codes to follow
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-11-17 at 17 43 37](https://user-images.githubusercontent.com/63132499/142222311-c77d0944-7e04-4c84-9d42-83a31fb4c586.png)


`import 'package:flutter/material.dart';
import 'package:flutter_slidable/flutter_slidable.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Slidable Example',
      home: Directionality(
        textDirection: TextDirection.rtl,
        child: Scaffold(
          // backgroundColor: Colors.grey,
          body: ListView(
            children: [
              Slidable(
                // Specify a key if the Slidable is dismissible.
                key: const ValueKey(0),

                // The start action pane is the one at the left or the top side.
                startActionPane: ActionPane(
                  // A motion is a widget used to control how the pane animates.
                  motion: const ScrollMotion(),

                  // A pane can dismiss the Slidable.
                  dismissible: DismissiblePane(onDismissed: () {}),

                  // All actions are defined in the children parameter.
                  children: const [
                    // A SlidableAction can have an icon and/or a label.
                    SlidableAction(
                      onPressed: doNothing,
                      backgroundColor: Color(0xFFFE4A49),
                      foregroundColor: Colors.white,
                      icon: Icons.delete,
                      label: 'Delete',
                    ),
                    // SlidableAction(
                    //   onPressed: doNothing,
                    //   backgroundColor: Color(0xFF21B7CA),
                    //   foregroundColor: Colors.white,
                    //   icon: Icons.share,
                    //   label: 'Share',
                    // ),
                  ],
                ),

                // The end action pane is the one at the right or the bottom side.
                // endActionPane: const ActionPane(
                //   motion: ScrollMotion(),
                //   children: [
                //     SlidableAction(
                //       // An action can be bigger than the others.
                //       flex: 2,
                //       onPressed: doNothing,
                //       backgroundColor: Color(0xFF7BC043),
                //       foregroundColor: Colors.white,
                //       icon: Icons.archive,
                //       label: 'Archive',
                //     ),
                //     SlidableAction(
                //       onPressed: doNothing,
                //       backgroundColor: Color(0xFF0392CF),
                //       foregroundColor: Colors.white,
                //       icon: Icons.save,
                //       label: 'Save',
                //     ),
                //   ],
                // ),

                // The child of the Slidable is what the user sees when the
                // component is not dragged.
                child: const Card(
                  color: Colors.yellowAccent,
                  elevation: 10,
                  child: ListTile(
                    title: Text('Slide me'),
                    // tileColor: Colors.indigo,
                  ),
                ),
              ),
              Slidable(
                // Specify a key if the Slidable is dismissible.
                key: const ValueKey(1),

                // The start action pane is the one at the left or the top side.
                startActionPane: const ActionPane(
                  // A motion is a widget used to control how the pane animates.
                  motion: ScrollMotion(),

                  // All actions are defined in the children parameter.
                  children: [
                    // A SlidableAction can have an icon and/or a label.
                    SlidableAction(
                      onPressed: doNothing,
                      backgroundColor: Color(0xFFFE4A49),
                      foregroundColor: Colors.white,
                      icon: Icons.delete,
                      label: 'Delete',
                    ),
                    SlidableAction(
                      onPressed: doNothing,
                      backgroundColor: Color(0xFF21B7CA),
                      foregroundColor: Colors.white,
                      icon: Icons.share,
                      label: 'Share',
                    ),
                  ],
                ),

                // The end action pane is the one at the right or the bottom side.
                endActionPane: ActionPane(
                  motion: const ScrollMotion(),
                  dismissible: DismissiblePane(onDismissed: () {}),
                  children: const [
                    SlidableAction(
                      // An action can be bigger than the others.
                      flex: 2,
                      onPressed: doNothing,
                      backgroundColor: Color(0xFF7BC043),
                      foregroundColor: Colors.white,
                      icon: Icons.archive,
                      label: 'Archive',
                    ),
                    SlidableAction(
                      onPressed: doNothing,
                      backgroundColor: Color(0xFF0392CF),
                      foregroundColor: Colors.white,
                      icon: Icons.save,
                      label: 'Save',
                    ),
                  ],
                ),

                // The child of the Slidable is what the user sees when the
                // component is not dragged.
                child: const ListTile(title: Text('Slide me')),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

void doNothing(BuildContext context) {}
`

**Comment by letsar** [comment]
I did test on the master branch and not the version on pub?
I'll redo the test this evening to be sure.

**Comment by letsar** [comment]
I redid the test, and I have no issue with rtl on the master branch (not yet published on pub.dev, so make sure to update your pubspec.yaml to the git instead).

**Comment by dryasbk** [comment]
Still does not work.
 I tried all possible ways I know to add it to my  (TextDirection.rtl ) application

![Screen Shot 2021-11-25 at 9 21 20 AM](https://user-images.githubusercontent.com/63132499/143390595-e4faa949-3be7-4c41-9ba8-d8c329c22fcb.png)

but work ok when adding startActionPane
![Screen Shot 2021-11-25 at 9 35 37 AM](https://user-images.githubusercontent.com/63132499/143391912-f805c00e-6df2-454e-8114-268321920604.png)

and endActionPane
![Screen Shot 2021-11-25 at 9 35 20 AM](https://user-images.githubusercontent.com/63132499/143391965-4327d9bc-533a-4f8e-b6c7-06329e646d6b.png)

**Comment by dryasbk** [comment]
fix bugs
useTextDirection: false

**Comment by amitkot** [comment]
@letsar master branch solves the RTL issues for my app as well. Do you know already when you plan to release it on pub.dev? 
Thanks!

**Comment by letsar** [comment]
I've just did it. It's available on the 1.2.0

**Comment by MomenYasser** [comment]
Guys this bug appeared again in latest version 3.1.1 :D
