### ISSUE TITLE
closeOnTap in IconSlideAction is rebuilding the child Widget

### ISSUE THREAD

**Issue by raphire08** [letsar/flutter_slidable#247]
I have a stateful widget in the child of a Slidable Widget. If I set closeOnTap as true on IconSlideWidget set as secondaryAction. On tap of the secondary action I am rebuilding the child widget via ValueListenableBuilder.
The child stateful widget is build twice (even the init method is called twice) on tap of the secondaryAction. 

If the close on tap is false, the init method is called only once.

Is there any method to close the secondaryAction and call the stateful widget only once??

**Comment by letsar** [comment]
Do you use the 1.0 version? I think I fixed it recently.

**Comment by raphire08** [comment]
I am using 0.6.0, will try with the latest version. Thanks

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
