### ISSUE TITLE
Checking slide ratio at the end of gesture

### ISSUE THREAD

**Issue by JostSchenck** [letsar/flutter_slidable#251]
I do not know if what I want to achieve is easily possible with flutter_slidable - I'm currently trying on 1.0.0-dev9. I wrote a ColorChangeMotion that changes the color of the ActionPane from grey, then yellow over orange to red, depending on how far I slide it. Now, what I want is to trigger some action if I end my gesture with the Slidable being in the yellow, orange or red area, depending on where I stopped sliding. The idea is to use simple gestures to show whether I felt comfortable with an item (swipe right, showing a green pane) or not so comfortable (swiping further left depending on my gut feeling). 

I just started trying around and I understand that using a SlidableNotificationListener I can catch some notifications in onNotification callback. There's a SlidableRatioNotification as a sub class, so I suppose I would have to test for the type of notification and could find out about the last ratio I was notified about. But I can't find something like an onOpen callback where I could trigger some action based on how far sliding went.

I have no idea if I made my problem clear -- if what I seek to achieve is not possible with your package, that's okay, but it was the nearest I could find to start on this. Thanks a lot for all the work you do!

**Comment by letsar** [comment]
Hi, thanks for this issue, it's very interesting! I think it would be possible but I'm not sure I understood all your requirements. Can you provide a video or images showing what you want to achieve? Otherwise I may understand it wrong and provide a wrong solution.

**Comment by JostSchenck** [comment]
Thank you very much for considering this! The attached screencast is from an app I'm writing for learning theatre lines. The idea is that the user swipes a line to the left, if he didn't remember, and swipes it to the right if he remembered. For the algorithm to figure out properly which parts to concentrate on, I want the user to be easily able to differentiate on _how good_ he remembered the line - the idea is that the more I swipe it to the right, the better I remembered, visualized by the changing color. I still have to pass a certain threshold, visualized by a grey background. I would then want to know in my trigger callback how far the tile had been dragged. I hope that becomes clear now :
![swipeable](https://user-images.githubusercontent.com/12062873/141374723-4cba93e1-ab3e-43fa-b04a-067a80345f2e.gif)

**Comment by letsar** [comment]
Thanks, yes, I understand what you want now. I'm away from keyboard but I don't see why it would not be possible.
You should pass create a widget which would listen for changes about the ratio on the SlidableController and pass it an Animation controller. Then when the ratio changes, you update the animation controller accordingly. I need to continue working on something else at the moment, but I'll come back here later with a complete implementation if what I said does not help you to do it.

**Comment by arslankaleem7229** [comment]
> Thanks, yes, I understand what you want now. I'm away from keyboard but I don't see why it would not be possible. You should pass create a widget which would listen for changes about the ratio on the SlidableController and pass it an Animation controller. Then when the ratio changes, you update the animation controller accordingly. I need to continue working on something else at the moment, but I'll come back here later with a complete implementation if what I said does not help you to do it.

This is exactly what I wanted to achieve to rotate the widget on the basis of readings of sliding... Can we achieve such this ? as this is realted to my problem so rather than creating an new question I asked here

![video-to-gif-converter](https://user-images.githubusercontent.com/49631685/143563899-0231025c-593f-401c-90b5-23f405ae63be.gif)

**Comment by letsar** [comment]
Hi @JostSchenck!

I created a specific example in the example project called **main_issue_251.dart**. I think this answer to your request, come back at me if it's not the case ;-)

**Comment by JostSchenck** [comment]
Great, thanks a lot, I will check it out :)

Romain Rastel ***@***.***> schrieb am Sa., 4. Dez. 2021,
16:19:

**Comment by annd22** [comment]
> Hi @JostSchenck!
> 
> I created a specific example in the example project called **main_issue_251.dart**. I think this answer to your request, come back at me if it's not the case ;-)

The example is great, but if I want a little feature like this:
- The current app make the color change to green after we drag over the ratio
- When I drag to max ratio -> lift my finger up -> the color still green (correct)
- But if I drag to max ratio -> I drag back to min ratio -> the color should be yellow (current is still green)
How can I implement this?
- I think we need to have a listener or something to check if the animation is executed by the user dragging, or by itself
- Maybe something like onDragStart, onDragEnd...?
