### ISSUE TITLE
open is not working after manually close

### ISSUE THREAD

**Issue by bksubhuti** [letsar/flutter_slidable#252]
`          slidable.open(actionType: SlideActionType.secondary);

// works the first time, works by tapping outside the listTiles inside the listview
// does not work if you swipe to undo the slide action
`

This code only works the first time or when tapping outside of the listview.
I think the state of "close" is not reset when it is "swiped to close" and therefore does not do anything.

I call this function for long press on GestureDetector.  It works fine the first time, but cannot be done  more than once within one build process.

**Comment by letsar** [comment]
Can you test on the 1.0 version? I won't maintain the 0.6 anymore.

**Comment by bksubhuti** [comment]
I noticed that there are quite a few incompatible changes in the upgrade.

I had help on this code, and I'm not sure how to upgrade it.
  void openSlidable(BuildContext context) {
    final slidable = Slidable.of(context);
    final isClosed = slidable!.renderingMode == SlidableRenderingMode.none;
    if (isClosed) {
      Future.delayed(Duration.zero, () {
        if (slidable.mounted) {
          slidable.open(actionType: SlideActionType.secondary);
        }
      });
    }
  }

**Comment by letsar** [comment]
You may try something like this instead:
```
void openSlidable(BuildContext context) {
  final controller = Slidable.of(context)!;
  final isClosed = controller.actionPaneType.value == ActionPaneType.none;
  if (isClosed) {
    controller.openEndActionPane();
  }
}
```

**Comment by bksubhuti** [comment]
It works.. but had to put a start action before.
The icon is now on the left side .. I guess I'll have to get used to it.
