### ISSUE TITLE
Swipe Indicator

### ISSUE THREAD

**Issue by YAPNALT** [letsar/flutter_slidable#259]
First of all, thank you for this good package. Now for my idea. Would it be possible to add a swipe indicator so that a user can see that the widget is swipeable. For example a swipe animation or something similar. Currently it's not visible for the user

**Comment by letsar** [comment]
Thank for the kind words. Yes you can totally do it without my help, you just need to add this indicator on the Slidable's child.

**Comment by apugoneappu** [comment]
@letsar is this already built-in or is this a feature request?

Thanks for the awesome widget!

**Comment by letsar** [comment]
This is not implemented, but this is something you can do.
