### ISSUE TITLE
SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length 

### ISSUE THREAD

**Issue by recepbuyukfirat** [letsar/flutter_slidable#26]
helllo, thank you for shared.  see the problem when i integration to preject in my project. how to solve this issues. (my english not good so sory) 
this problem output:
SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length

help me please

**Comment by letsar** [comment]
Hi @recepbuyukfirat, can you paste the minimal code to reproduce this issue?

**Comment by recepbuyukfirat** [comment]
Sory. i could not answer because i had another jops. write my flutter_slidable code the following: 


`                        return new Slidable(
                          key: new Key(_messages[index].toString()),
                          controller: slidableController,
                          direction:Axis.horizontal,
                          delegate: _getDelegate(item.id),
                          actionExtentRatio: 0.25,
                          child: new Column(
                            crossAxisAlignment: isReceived
                                ? CrossAxisAlignment.start
                                : CrossAxisAlignment.end,
                            mainAxisAlignment: isReceived
                                ? MainAxisAlignment.start
                                : MainAxisAlignment.end,
                            children: <Widget>[
                              new Container(
                                margin: isReceived ? new EdgeInsets.only(
                                    left: 10.0, right: MediaQuery
                                    .of(context)
                                    .size
                                    .width / 4, top: 5.0, bottom: 5.0) :
                                new EdgeInsets.only(left: MediaQuery
                                    .of(context)
                                    .size
                                    .width / 4, right: 10.0, top: 5.0, bottom: 5.0),
                                padding: new EdgeInsets.only(
                                    left: 20.0, right: 20.0, top: 10.0, bottom: 10.0),
                                decoration: new BoxDecoration(
                                  color: Colors.grey.withOpacity(0.1),
                                  borderRadius: BorderRadius.circular(10.0),
                                ),
                                child: new Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: <Widget>[
                                    new Text(isReceived ? senderName : "Siz", style: TextStyle(
                                        color: isReceived ? Colors.red : Colors.green),),
                                    new Text(content, style: TextStyle(color: Colors.white),),
                                    SizedBox(height: 6.0,),
                                    new Text(
                                      date.toString().substring(0, 16),
                                      style: TextStyle(color: Colors.grey, fontSize: 12.0),
                                      textAlign: TextAlign.end,
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                          actions: <Widget>[
                            new IconSlideAction(
                              caption: 'Delete',
                              color: Colors.red,
                              icon: Icons.delete,
                              onTap: () => deleteMessage(),
                            ),
                          ],
                          secondaryActions: <Widget>[
                            new IconSlideAction(
                              caption: 'Delete',
                              color: Colors.red,
                              icon: Icons.delete,
                              onTap: () => deleteMessage(),
                            ),
                          ],
                        );`

**Comment by letsar** [comment]
Hi @recepbuyukfirat, sorry but I cannot run the code you provided. It's not independent of the rest of your code.
Can you please, write a sample that I could simply copy and paste in a file and run it?

**Comment by recepbuyukfirat** [comment]
I think this problem is caused by the change of APIs, so tanks for your interest

**Comment by MatiDeve** [comment]
Hi, I had the same error. In my case, the problem wasn't the TextFormField. It was because of the key inside the Form widget. If you use a key, the general widget must be StatefulWidget, not StatelessWidget.

Wrong code

```
    class MyWidget extends StatelessWidget{
      final GlobalKey<FormState> _formKey = GlobalKey<FormState>(); 
      @override
      Widget build(BuildContext context) {
        // TODO: implement build
        return Scaffold(
          body: Form(
            key: _formKey,
            child: TextFormField(),
          ),
        );
      }
    }
```

Right Code

```
class MyWidget extends StatefulWidget{
      @override
      State<StatefulWidget> createState() {
        // TODO: implement createState
        return _MyWidgetState();
      }
    }
    
    class _MyWidgetState extends State<MyWidget>{
      final GlobalKey<FormState> _formKey = GlobalKey<FormState>(); 
      @override
      Widget build(BuildContext context) {
        // TODO: implement build
        return Scaffold(
          body: Form(
            key: _formKey,
            child: TextFormField(),
          ),
        );
      }
    }
```
