### ISSUE TITLE
onPressed problems

### ISSUE THREAD

**Issue by sigjak** [letsar/flutter_slidable#264]
In version 1.1.0 the onPressed function seems to be running on build but not when pressed. In a ListView.builder with a simple function, which prints index of list when run, the index is printed for the entire list on build but not when the slidable is pressed.

**Comment by sigjak** [comment]
I assumed a function should be called in onPressed but that is not the case. My misunderstanding.  Maybe the readme could be more informative.

**Comment by aaronkelton** [comment]
I had a similar problem trying to simply print. Trying to do so without a `context` argument raised the following error: `Error: The argument type 'void Function()' can't be assigned to the parameter type 'void Function(BuildContext)?'.` I found this behavior to be surprising. I did not expect it.
```dart
endActionPane: ActionPane(
  children: [
    SlidableAction(
      onPressed: () => print('hey'),
      label: 'Test',
    ),
  ],
  motion: ScrollMotion(),
),
```

To fix the error, you can pass `context` or really just some dummy throw away variable, like the underscore `_`, e.g.
```dart
endActionPane: ActionPane(
  children: [
    SlidableAction(
      onPressed: (_) => print('hey'),
      label: 'Test',
    ),
  ],
  motion: ScrollMotion(),
),
```

**Comment by leonacky** [comment]
> I had a similar problem trying to simply print. Trying to do so without a `context` argument raised the following error: `Error: The argument type 'void Function()' can't be assigned to the parameter type 'void Function(BuildContext)?'.` I found this behavior to be surprising. I did not expect it.
> 
> ```dart
> endActionPane: ActionPane(
>   children: [
>     SlidableAction(
>       onPressed: () => print('hey'),
>       label: 'Test',
>     ),
>   ],
>   motion: ScrollMotion(),
> ),
> ```
> 
> To fix the error, you can pass `context` or really just some dummy throw away variable, like the underscore `_`, e.g.
> 
> ```dart
> endActionPane: ActionPane(
>   children: [
>     SlidableAction(
>       onPressed: (_) => print('hey'),
>       label: 'Test',
>     ),
>   ],
>   motion: ScrollMotion(),
> ),
> ```

still get error
