### ISSUE TITLE
Unable to get slidable controller by using Slidable.of(context) in child widget

### ISSUE THREAD

**Issue by Bikram-Shrestha** [letsar/flutter_slidable#268]
First of all thanks for this excellent package. 

I am unable to get the SlidableController within the child of Slidable. I have moved to 1.1.0.

``` 
 Slidable(
                  endActionPane:
                      ActionPane(motion: const ScrollMotion(), children: [
                    SlidableAction(
                      onPressed: (_) {},
                      icon: Icons.delete,
                      label: 'Delete',
                    )
                  ]),
                  child: ListTile(
                    onTap: () {
                      Slidable.of(context)?.openEndActionPane();
                    },
                    title: Text('Slide Demo'),
                  ),
                );
```

The behaviour I am expecting is that it will open endActionPane when I press ListTile. Thanks

**Comment by Bikram-Shrestha** [comment]
It is working as intended when I make the Container wrap with Gesture detector.  So I am closing it.

**Comment by saigopin** [comment]
@Bikram-Shrestha can you share snippet? i am facing same issue

**Comment by Bikram-Shrestha** [comment]
@saigopin as mentioned in my comment. I was able to access controller when I do something like this.
``` dart
  Slidable(
      endActionPane: ActionPane(motion: const ScrollMotion(), children: [
        SlidableAction(
          onPressed: (_) {},
          icon: Icons.delete,
          label: 'Delete',
        )
      ]),
      child: WidgetWithGestureDetector(
        onTap: () {
          Slidable.of(context)?.openEndActionPane();
        },
      ),
    );
```

If you will like I will make this open

**Comment by Picorete** [comment]
i am facing same issue, and wrap with Gesture detector did not work for me

**Comment by Bikram-Shrestha** [comment]
Reopening due to more people having similar issue

**Comment by tigrenok00** [comment]
+1

**Comment by letsar** [comment]
This is because the context you use is above the Slidable widget. Wrap the Slidable's child with a Builder widget or put it in a specific one and it will be ok. See https://stackoverflow.com/a/51304732 for a better explanation.
