### ISSUE TITLE
Shape on actions

### ISSUE THREAD

**Issue by oscarshaitan** [letsar/flutter_slidable#269]
Previous the migration, the actions can be wrapped with other widgets allowing to use for example clipRect
like the image
![Screen Shot 2021-11-26 at 1 27 09 PM](https://user-images.githubusercontent.com/9093952/143619647-20094b2f-5b29-4b4c-80e3-8a8ec422cdb8.png)
Now is not possible due this errors: 
```
Incorrect use of ParentDataWidget 
DrawerMotion only supports children with non-zero flex 
```

the work around is surround the final widget with `Flexible` that shows the actions.
leaving just `Incorrect use of ParentDataWidget`
and this dont allow the render on release mode
![Screen Shot 2021-11-26 at 1 45 23 PM](https://user-images.githubusercontent.com/9093952/143620845-b8bb1428-01d0-428d-978e-8644f9eb59ea.png)

Also previous migration the text can be displayed, now shows the overflow.
![Screen Shot 2021-11-26 at 1 55 02 PM](https://user-images.githubusercontent.com/9093952/143621516-be16a485-82dc-4e0e-aa13-572d3cae7fe5.png)

**Comment by letsar** [comment]
This is not really documented but you need to add an expanded above your custom action if CustomSlidableAction is not the good fit for your needs.

**Comment by oscarshaitan** [comment]
when do that get the gray widgets on release and profile mode

**Comment by abisao1** [comment]
I have kinda similar issue. I wanna add SlidableAction with circular radius. How can I do that?

**Comment by dndeus** [comment]
Still no a suggestion on this one??

**Comment by letsar** [comment]
@dndeus the suggestion is here: https://github.com/letsar/flutter_slidable/issues/269#issuecomment-986211111
I'm closing this since we can do it with `CustomSlidableAction` or just an `Expanded` widget..
