### ISSUE TITLE
Feature Request [VoidCallback? onLongPress]

### ISSUE THREAD

**Issue by nikhilbadyal** [letsar/flutter_slidable#270]
Hey, 
I would like to request onLongPressHandler for the SlidableAction.  I went through the code and found it all boils down to Outline Button.

actions.dart 
```
OutlinedButton(
          onPressed: () => _handleTap(context),
          style: OutlinedButton.styleFrom(
            backgroundColor: backgroundColor,
            primary: effectiveForegroundColor,
            onSurface: effectiveForegroundColor,
            shape: const RoundedRectangleBorder(),
            side: BorderSide.none,
          ),
          child: child,
        ),
```

Outline Button also has onLongHanlder. Can you also enable it as parameter.

**Comment by nikhilbadyal** [comment]
I have implemented this in my fork. If you want I can make a PR for the same.

**Comment by letsar** [comment]
SlidableAction are juste here to give something to work with easily but it's not intented for all usage. The best to do in that case is to create your own SlidableActions like you did.
