### ISSUE TITLE
Slidable in PageView

### ISSUE THREAD

**Issue by water-user** [letsar/flutter_slidable#271]
I have 5 screens in a PageView widget, the third screen is a ListView, my ListView using Slidable.
I'm using Slidable only for delete a record by swipe from right to left (endActionPane).
I have a problem when i'm trying to go back to the second screen by swipe from left to right, the swipe is not response, and i can't go back to the second screen, that happen because of the Slidable widget, how can i fix it?

**Comment by letsar** [comment]
In my opinion it's not a good idea to have two elements which can be scrolled in the same direction and it's tricky to implement. I won't add it in the package unless there is a good PR about this.
