### ISSUE TITLE
DismissablePane with old dragDismissible false feature?

### ISSUE THREAD

**Issue by corcoran** [letsar/flutter_slidable#274]
We're trying to create functionality possible in 0.6 where the SlidableAction wasn't drag dismissible (`dragDismissible: false`), but still showed the animation when the button itself as tapped. ([video](https://photos.app.goo.gl/DnQyVqhyTBCXw41T7)). This was done with the following code:

```
  secondaryActions: [
    SlideActionButton(
      icon: const Icon(Icons.delete_outline_rounded),
      label: 'Remove',
      color: ColorUtils.redBadge,
      onTap: () => slidableController.activeState?.dismiss(
        actionType: SlideActionType.secondary,
  ],
  dismissal: SlidableDismissal(
    child: const SlidableDrawerDismissal(),
    dragDismissible: false,
    onDismissed: (actionType) {
      if (actionType == SlideActionType.secondary) {
        _removeItem<T>(type, watchlist[index].item);
      }
    },
  ),
```

In 1.1, dragDismissible is missing, but we're able to semi-reproduce the same functionality ([video](https://photos.app.goo.gl/nU7LGBz4ML24sg2C6))

The main difference being we can't trigger an animated dismiss without creating a `DismissiblePane`, setting `closeOnCancel: true` and returning false with `confirmDismiss` in order to prevent the user from dragging to completion. Ideally the user is unable to slide the SlidableAction past the max point, disable dragDismissible, while still showing the old dismiss animation. Here's the code for our semi-working new version:

```
    endActionPane: ActionPane(
      motion: const DrawerMotion(),
      extentRatio: 0.25,
      children: [
        SlidableAction(
          icon: Icons.delete_outline_rounded,
          autoClose: false,
          label: 'Remove',
          backgroundColor: ColorUtils.redBadge,
          onPressed: (c) {
            Slidable.of(c).dismiss(
              ResizeRequest(300.milliseconds, () {
                _removeItem<T>(type, watchlist[index].item);
              }),
              duration: 300.milliseconds,
            );
          },
        ),
      ],
      dismissible: DismissiblePane(
        closeOnCancel: true,
        confirmDismiss: () => Future.value(false),
        onDismissed: () {},
      ),
    ),
``` 

Is the previous behavior possible in the new version?

Thanks for the fantastic library :)

**Comment by letsar** [comment]
Hi! I've just added a dragDismissible property on ActionPane. It's only available on master for the moment. Can you test it?

**Comment by corcoran** [comment]
Tested and it appears to work well, thank you!
