### ISSUE TITLE
`extentRatio` applies to entire list of children, instead of to each element

### ISSUE THREAD

**Issue by corcoran** [letsar/flutter_slidable#281]
It appears as though `extentRatio` went from applying the value to every child in `children`, to applying the value to the entire list of children.

e.g.

In 0.6, if I set `actionExtentRatio` to 0.25 and had 2 children, each child would be 0.25, where as now it applies 0.25 to the entire list, regardless of how many children exist.

**Comment by letsar** [comment]
Yes this is intended. I should had documented that, sorry. The advantage is that now, you can have an action that will take 2/3 of the available space and the other 1/3 if you want.
