### ISSUE TITLE
Manually open slider

### ISSUE THREAD

**Issue by britannio** [letsar/flutter_slidable#282]
I am using the package for a web app and the expectation is to tap on the edge of a slidable widget to open it. Is there a way to manually open the slider in such cases? And if not, could a controller be introduced to allow for such behaviour? 

May be related to https://github.com/letsar/flutter_slidable/issues/163

**Comment by letsar** [comment]
[You can :-)](https://github.com/letsar/flutter_slidable/wiki/FAQ#how-can-i-open-the-slidable-programmatically)
