### ISSUE TITLE
Rounded Corners

### ISSUE THREAD

**Issue by Hesham-Dev-LY** [letsar/flutter_slidable#283]
consider to add the option that make the corners rounded with a given radius .

**Comment by pushpendraKh** [comment]
In addition to this, is it possible to add a margin?

Like I want to add some margin after Slidable is open. 

<img width="319" alt="Screenshot 2021-12-13 at 14 25 33" src="https://user-images.githubusercontent.com/11942435/145781557-51b3dee2-0e5e-4eff-9ce4-92b32ff31797.png">

**Comment by ljx0520** [comment]
rewrite "CustomSlidableAction" will do

**Comment by AmosHuKe** [comment]
@Hesham-Dev-LY @ @pushpendraKh   
Here: [#297 ](https://github.com/letsar/flutter_slidable/issues/297#issuecomment-1018240738)
