### ISSUE TITLE
Can the height be allowed?

### ISSUE THREAD

**Issue by qiaoshouqing** [letsar/flutter_slidable#284]
Can the height be allowed? Because my card has rounded corners and shadows, the height of the action is higher than the card, which is very unsightly. I tried various customizations but couldn't solve my problem.

**Comment by nipun-sehrawat** [comment]
You can achieve this by defining your own widget instead of using CustomSlidableAction.  For example, the following displays the action button on a card:

`Expanded(
      child: SizedBox.expand(
        child: Card(
          elevation: 5,
          margin: const EdgeInsets.symmetric(vertical: 8, horizontal: 5),
          child: OutlinedButton(
            onPressed: () {},
            style: OutlinedButton.styleFrom(
              backgroundColor: const Color(0xFFFE4A49),
              primary: Colors.white,
              side: BorderSide.none,
            ),
            child: const Icon(Icons.delete),
          ),
        ),
      ),
    )`

**Comment by rt234cw** [comment]
> You can achieve this by defining your own widget instead of using CustomSlidableAction. For example, the following displays the action button on a card:
> 
> ```
> Expanded(
>       child: SizedBox.expand(
>         child: Card(
>           elevation: 5,
>           margin: const EdgeInsets.symmetric(vertical: 8, horizontal: 5),
>           child: OutlinedButton(
>             onPressed: () {},
>             style: OutlinedButton.styleFrom(
>               backgroundColor: const Color(0xFFFE4A49),
>               primary: Colors.white,
>               side: BorderSide.none,
>             ),
>             child: const Icon(Icons.delete),
>           ),
>         ),
>       ),
>     )
> ```

But how to dismiss the slidableaction after pressed?
