### ISSUE TITLE
Slidable1.1.0,How to close only one of list? "Slidable.of(context)" return "null"

### ISSUE THREAD

**Issue by yingzi1208** [letsar/flutter_slidable#286]
void closeSlidable(context) {
    if (slidablecontroller == null) {
      slidablecontroller = Slidable.of(context);
      // slidablecontroller = SlidableController(this);
    }
    if (slidablecontroller != null) {
      SlidableGroupNotification.dispatch(
        context,
        SlidableAutoCloseNotification(
          groupTag: 'loveSellerList',
          controller: slidablecontroller!,
        ),
      );
    } else {
      print("null");
    }
  }

I want to close only one,but "Slidable.of(context)" return "null"

@letsar I want to close it when I go the next page.

**Comment by yingzi1208** [comment]
@letsar

**Comment by pushpendraKh** [comment]
@yingzi1208 Do you want to close the sliding tile when going to the next page? (basically on tap of tile, it should close)

**Comment by yingzi1208** [comment]
> @yingzi1208进入下一页时要关闭滑动磁贴吗？（基本上是点击瓷砖，它应该关闭）
Slidable(
   groupTag: 'list',
   key: ValueKey("$index"),
   direction: Axis.horizontal,
   endActionPane: ActionPane(
      dismissible: DismissiblePane(onDismissed: () {} ),
      motion: ScrollMotion(),
      extentRatio: 1,
      children: [
           GestureDetector(
               behavior: HitTestBehavior.opaque,
               onTap: () {
               /*go to  next page and close the sliding*/
               },
               child: Container()
             ),
           GestureDetector(
              behavior: HitTestBehavior.opaque,
              onTap: () {mapShow(index);},
              child: Container()
           ),
       ]
     ),
)

This is my code,  it not close

**Comment by pushpendraKh** [comment]
Yes, you don't need to do this. 

Going with the next release, I think, this will be added to [SlidableAutoCloseBehavior](https://github.com/letsar/flutter_slidable/blob/master/lib/src/auto_close_behavior.dart#L8). You will just need to wrap your list view with `SlidableAutoCloseBehavior`

If you want this now, you can use the `master` branch in pubspec.

**Comment by yingzi1208** [comment]
@pushpendraKh 
My English is not very good.But,thank you very much.Now,I used SlidableAutoCloseBehavior,it can close other Slidable when click it,but it can't close itself. I need close itself when click Slidable! Will the next release be added?

**Comment by pushpendraKh** [comment]
Yes, I hope so. But as I said, if you want to use it now, you can refer to master branch in your pubspec. You can read more about it [here](https://dart.dev/tools/pub/dependencies)

**Comment by yingzi1208** [comment]
Ok, I see. thank you very much!  ԅ(¯﹃¯ԅ)

**Comment by JiaoLiu** [comment]
> void closeSlidable(context) { if (slidablecontroller == null) { slidablecontroller = Slidable.of(context); // slidablecontroller = SlidableController(this); } if (slidablecontroller != null) { SlidableGroupNotification.dispatch( context, SlidableAutoCloseNotification( groupTag: 'loveSellerList', controller: slidablecontroller!, ), ); } else { print("null"); } }
> 
> I want to close only one,but "Slidable.of(context)" return "null"
> 
> @letsar I want to close it when I go the next page.

**Comment by yingzi1208** [comment]
@JiaoLiu 
I tried. This method is feasible.Thank you very much.

**Comment by JiaoLiu** [comment]
> 
i think you should not care about whether the slider is open or not, because the function 'close' will close the slider if it is open & do nothing if it's not open.

BTW, you can maintain the status of the cell by yourself (use a global list to store them).

**Comment by gopibathini** [comment]
@JiaoLiu i want close thekey board  when the  slider is open
