### ISSUE TITLE
Hello, How to allow only one Slidable at a time to be open in listView

### ISSUE THREAD

**Issue by niiitish1** [letsar/flutter_slidable#287]

**Comment by JiaoLiu** [comment]
> _No description provided._
I think you can define a global list to store the state of the listview & control the action of each cell.
like [0,0,0,1,0,0] means cell 3 is open, then the rest of Slidable cells can't be open.

BTW, flutter_swipe_action_cell will be better to satisfy your demand.

**Comment by niiitish1** [comment]
ok..
Thanks for your help......
