### ISSUE TITLE
Can't dismiss with action tap

### ISSUE THREAD

**Issue by Velkamhell97** [letsar/flutter_slidable#293]
I try to dismiss the slidable when i tap in action, but this does not work, this is my code:

```
SlidableAction(
    onPressed: (context){
      Slidable.of(context)!.dismiss(
        ResizeRequest(
          const Duration(seconds: 2), 
          () {
            print('Dismiss from Button');
          }
        ),
        duration: const Duration(seconds: 2)
      );
    },
    backgroundColor: Colors.red,
    // foregroundColor: Colors.white,
    icon: Icons.delete,
    label: 'Delete',
  ),
```

Is this possible ?

**Comment by Complay** [comment]
I don't know if this is a bug, but you need to add a listener to dismissGesture before use dismiss method:

`Slidable.of(context)!.dismissGesture.addListener(() { 
     print('dismissed');
});`

**Comment by zzz2016** [comment]
same issue...
In my case , setting the autoClose to false solve the problem.

**Comment by mbarmettler** [comment]
how to solve this on "DismissablePane" ?

i want the same behaviour as in the SlideableActions onPressed event.

my SlidableAction looks like this - and works with confirmation of user, before deletion of element:
`                    SlidableAction(
                      autoClose: false,
                      backgroundColor: Color(0xFFFE4A49),
                      foregroundColor: Colors.white,
                      icon: Icons.delete,
                      label: MobileLocalization.of(context).viewUserEditDeleteTemplateSwipeLabel,
                      onPressed: (BuildContext context) {
                        _deleteLayer(context, layer);
                      },
                    ),`


but on the main "slideable Action" - with gesture sliding to right - should also wait for confirmation.
any idea how to achieve this?

                `startActionPane: ActionPane(
                  extentRatio: 0.25,
                  motion: const ScrollMotion(),
                  dismissible: DismissiblePane(onDismissed: () async {
                                _deleteLayer(context, layer);
                              }),
...
)`

**Comment by letsar** [comment]
Yes it's possible, but you need to set `autoClose` to false before, and then like you did, in the `onPressed` of your action you can do that:
```dart
onPressed: (context) {
  Slidable.of(context)?.dismiss(
      ResizeRequest(Duration(milliseconds: 300), () {}));
},
```
