### ISSUE TITLE
how to make tap to open slidable using flutter_slidable package?

### ISSUE THREAD

**Issue by twittergadungan** [letsar/flutter_slidable#300]
I am using version 1.2.0

to achieve this: https://i.stack.imgur.com/hqfnx.png

currently I use this code below
```

Slidable(
              child: ProductListItem(product: product),
              endActionPane: ActionPane(
                motion: const StretchMotion(),
                children: [
                  SlidableAction(
                    onPressed: (context) {
                      //
                    },
                    backgroundColor: Colors.orange,
                    foregroundColor: Colors.white,
                    icon: Icons.edit,
                    label: "edit".tr(),
                  ),
                  SlidableAction(
                    onPressed: (context) {
                      //
                    },
                    backgroundColor: Colors.red,
                    foregroundColor: Colors.white,
                    icon: Icons.delete,
                    label: "delete".tr(),
                  ),
                ],
              ),
            ),
```

I need to swipe in the right side to open that endPaneActions.

what I want is ....

if I tap that list item, then it will programmatically open that endPaneActions. how to do that?

from the tutorial on Youtube in  [https://www.youtube.com/watch?v=uuScuU3Vqlc&t=403s](url) , it seems I can use the code below

```
final slidable = Slidable.of(context);
final isClosed = slidable.renderingMode == SlidableRenderingMode.none;

if (isClosed) {
   slidable.open();
}
```

but it seems that code is obsolete, I can't find `.renderingMode `method on version 1.2.0

what is the latest version to programmatically open 'end actions pane' ?

**Comment by austinn** [comment]
@twittergadungan 

This will work for opening
```
slidable?.openEndActionPane(
  duration: const Duration(milliseconds: 500),
  curve: Curves.decelerate,
);
```

Similarly to close you can do
```
slidable?.close(
  duration: const Duration(milliseconds: 500),
  curve: Curves.decelerate,
);
```

However I have not found a way to determine if the Slidable is currently open without using a StatefulWidget

**Comment by Albertbol** [comment]
@austinn how do you achieve it with StatefulWidget?

**Comment by Albertbol** [comment]
What about:
```
   final slidable = Slidable.of(sliderContext);
    slidable?.direction.value == 0
        ? slidable?.openEndActionPane()
        : slidable?.close();
```

**Comment by gopibathini** [comment]
@Albertbol    i have tried the  above code  you mentioned , iam not able to open second slide on first click , when i tap on second time  on another list item, it is just closing the first slide not opening the second slidable

**Comment by twittergadungan** [comment]
@austinn 
could you please copy and paste your full code?
I always get the slidable null

```
          Slidable(
              child: GestureDetector(
                child: ProductListItem(),
                onTap: () {

                  final slidable = Slidable.of(context);  // always get null in here
                  slidable?.openEndActionPane(
                    duration: const Duration(milliseconds: 500),
                    curve: Curves.decelerate,
                  );

                },
              )
           )
```

**Comment by twittergadungan** [comment]
@gopibathini check this answer: https://stackoverflow.com/questions/70573686/how-to-make-tap-to-open-slidable-using-flutter-slidable-package/71892578#71892578

**Comment by gopibathini** [comment]
@twittergadungan  iam able to open the slide by tapping on it. But it is not working as auto close , on tapping auto close functionality not working . when i tap on first list item it is getting open later when i tap on second  list item , the first list item just closes , second list item slide is not opening

**Comment by letsar** [comment]
You should set `autoClose` to false in that case. And the way to do it, in to call `Slidable.of(context).openXXXActionPane() `inside the `onPressed` callback of the `SlidableAction`.

**Comment by Dev-Adnani** [comment]
How To Open Slidable In Stateful Widget , In InitState ?
