### ISSUE TITLE
ActionPane handle empty children

### ISSUE THREAD

**Issue by iamchathu** [letsar/flutter_slidable#304]
After upgrade to 1.1.0,

 Slidable(
      startActionPane: ActionPane(
        motion: const DrawerMotion(),
        extentRatio: 0.27,
        children: <Widget>[
          if (widget.someThingEnabled)
            SlidableAction(
              label: 'Something',
              backgroundColor: Colors.lightGreen,
              icon: Icons.attach_money,
              onPressed: (_) => widget.onSomething(),
            ),
          if (widget.isOtherThingEnabled)
            SlidableAction(
              label: 'Other Thing',
              backgroundColor: Colors.yellow,
              icon: Icons.local_atm_outlined,
              onPressed: (_) => widget.onOtherthing(),
            ),
        ],
      ),
...)

When startActionPane's ActionPane children were empty previous version it didn't had sliding ability. With current version it does slide with empty space.

**Comment by letsar** [comment]
If there are no actions, you should not set the `ActionPane`.
