### ISSUE TITLE
How do you set width to your slidable

### ISSUE THREAD

**Issue by vedadovsky** [letsar/flutter_slidable#308]
Hello what I'm trying to do is have a width of 30 (or some other value for instance MediaQuery.of(context).size.width * 0.2) for my slidable with only one icon but when I add only one Icon into SlidableAction the width is almost half of my ListTile.

What is my best approach to solve this issue, \
looking forward to your response

**Comment by sumitsharansatsangi** [comment]
Use this fork , [https://github.com/sumitsharansatsangi/flutter_slidable.git](https://github.com/sumitsharansatsangi/flutter_slidable.git)

It allows to pass widget.
Enjoy and closed this issue.

**Comment by app777** [comment]
U can use extentRatio parameter to set the width.

endActionPane: ActionPane(
        extentRatio: 0.2,  // default is 0.5
