### ISSUE TITLE
Allow SlideableAction label and icon to be Widgets

### ISSUE THREAD

**Issue by hamishjohnson** [letsar/flutter_slidable#317]
If the slideable action label and icon were widgets then they could be more customizable... right now I have difficulty setting the size of icons, and I don't use material icons, instead I use Font awesome icons

**Comment by sumitsharansatsangi** [comment]
Use this fork
[https://github.com/sumitsharansatsangi/flutter_slidable.git](https://github.com/sumitsharansatsangi/flutter_slidable.git)

**Comment by letsar** [comment]
You can use `CustomSlidableAction` to do what you want.
