### ISSUE TITLE
Smooth closing when dismissing or pressing a button

### ISSUE THREAD

**Issue by nicolasvahidzein** [letsar/flutter_slidable#319]
Hello,

is there a way to have the drawer close when we press a button?

Same question when we use the dismiss swipe action with a false return (in order to prevent the item from being dismissed).

The drawer does not close like you would expect, it just snaps back to it's original closed state.

Maybe i am not implementing it properly but i thought i would ask.

thanks.

**Comment by nicolasvahidzein** [comment]
@HammadBukhari

**Comment by HammadBukhari** [comment]
You can add this to the onTap of button to close the drawer/slidable 
```dart
Slidable.of(context)?.close();
`````
For your second question, the animation seems fine on my side. Are you looking at the animation in debug mode? The animations can be janky in it, try testing it on release mode.

**Comment by nicolasvahidzein** [comment]
I'll have to do it in release mode because i am seeing no changes whatsoever.

**Comment by tologonkudaiberdiuulu** [comment]
@HammadBukhari `Slidable.of(context)?.close();` not closing slidable. Anyone has same issue?

**Comment by nicolasvahidzein** [comment]
I finally ran in in release mode and it is not smooth at all. Anyone was able to fix this?

**Comment by nicolasvahidzein** [comment]
@HammadBukhari do you have sample reproducible code i can run? Thanks in advance.

**Comment by HammadBukhari** [comment]
> @HammadBukhari `Slidable.of(context)?.close();` not closing slidable. Anyone has same issue?

Make sure you are passing the correct context. If unsure, use the Builder widget and its context.

**Comment by HammadBukhari** [comment]
> @HammadBukhari do you have sample reproducible code i can run? Thanks in advance.

I did share some code in your last post. Try to isolate the Slidable widget and make sure there isn't another widget causing the issue.

**Comment by HammadBukhari** [comment]
It should not jump back to its original position. As I mentioned, Try to isolate the Slidable widget with no operations in confirmDismiss except returning false. The jank/immediate jump back to the original position can be due to heavy processing on the main isolate and always test the smoothness of animations on release mode, debug mode is always janky.

**Comment by nicolasvahidzein** [comment]
Please send a complete code that is not janky on your side so i can test it please. All of mine are that way. I dont understand what you are implying by “isolate”.

**Comment by nicolasvahidzein** [comment]
You were right @HammadBukhari, i had a setstate somewhere in my code that caused a break in the animation i believe. I isolated the actions like you said and it's smooth. Thanks a lot for your help.

**Comment by nicolasvahidzein** [comment]
BTW, no need to run it in release mode, in debug the animation was perfectly smooth as it needed to be.
