### ISSUE TITLE
SlidableAction tooltip and text style options

### ISSUE THREAD

**Issue by dzliergaard** [letsar/flutter_slidable#320]
I'd like to be able to control the text style of the labels of the SlidableActions, whether it be with a labelStyle parameter or just knowing which element of ThemeData it's pulling the theme from (it's unclear from the code itself).

If that's not possible, I'd like to at least specify tooltip text to appear when long pressing the icon, for a little extra context.

**Comment by sumitsharansatsangi** [comment]
Added Widget in place of String for label.
Use this [https://github.com/sumitsharansatsangi/flutter_slidable.git](https://github.com/sumitsharansatsangi/flutter_slidable.git)

**Comment by dzliergaard** [comment]
Is there a pull request to merge that change into this package?

**Comment by sumitsharansatsangi** [comment]
@dzliergaard , [Here](https://github.com/letsar/flutter_slidable/pull/324) is the pull request.
 Please merge it.

**Comment by dzliergaard** [comment]
I'm not a contributor of the project, so I don't have approval access.

**Comment by letsar** [comment]
You can with `CustomSlidableAction`.
