### ISSUE TITLE
Add controller for swipeLeft() or swipeRight() or hide()

### ISSUE THREAD

**Issue by nuzhata** [letsar/flutter_slidable#322]
be able to swipe left or right from another widget. 
eg: 
ListTile( 
     onLongPress:  (){
           _controller.swipeLeft();
     }
)

**Comment by hassanannajjar** [comment]
@nuzhata 
+1

**Comment by letsar** [comment]
You can do it from within the Slidable's content. If you want another widget to be able to do it, you need to pass it its SlidableController.
