### ISSUE TITLE
groupTag doesn't work

### ISSUE THREAD

**Issue by yangxiaoweihn** [letsar/flutter_slidable#330]
version: 1.2.0
groupTag property doesn't work

**Comment by derekedelaney** [comment]
I am also seeing this in 1.2.0 😞

**Comment by cekrozl1** [comment]
Version 1.3.0 -> groupTag still doesn't work. 

Is it possible that it must be used exclusively in a list of Slidables?

**Comment by callawey** [comment]
Its working, you just need to wrap it with SlidableAutoCloseBehavior

**Comment by derekedelaney** [comment]
@callawey Thanks for pointing that out. It does work with `SlidableAutoCloseBehavior`. Here's the documentation I missed the first time looking through the docs. https://github.com/letsar/flutter_slidable/wiki/FAQ#how-to-keep-only-one-slidable-open

**Comment by huangxin813** [comment]
> 

it works for me. I wrap the whole ListView in SlidableAutoCloseBehavior, and set a same groupTag for each item, then it works. :)
