### ISSUE TITLE
How do I remove the Slidable widget from application.

### ISSUE THREAD

**Issue by purubagga** [letsar/flutter_slidable#331]
So when I dismiss the tile using slidable I get thrown an error that A dismissed slidable widget is still part of the tree

**Comment by johnwargo** [comment]
@purubagga probably always best to show your code

**Comment by letsar** [comment]
remove if from your widget tree then. It's the same behavior as in [Dismissible](https://api.flutter.dev/flutter/widgets/Dismissible-class.html).
