### ISSUE TITLE
Разрабы дауны!

### ISSUE THREAD

**Issue by gramorEticon** [letsar/flutter_slidable#332]
Какого то хера вылазят ошибки!
У вас самая отвратительная документация которую я когда либо видел!
Или почините свой кал или удаляйтесь с pub.dev!!!!!!!!!!!

**Comment by shkvoretz** [comment]
The comment is in Russian. I speak fluent Russian and the subject of the issue he raised literally translates as "developers are retarded". Admins, please close the issue and report the user?  Thanks.

**Comment by AmirJaber97** [comment]
What can you expect. he's from Siberia..
