### ISSUE TITLE
Flutter 3.0 build error

### ISSUE THREAD

**Issue by gisvanjinathan** [letsar/flutter_slidable#338]
After upgrading to Flutter 3.0 we got a build problem when using flutter_slidable.

Log:

../Library/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_slidable-1.2.0/lib/src/auto_close_behavior.dart:391:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../Library/Developer/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((Duration _) {

**Comment by bct-fbo** [comment]
Quickly fixed it, now we just wait for the author to accept it.

https://github.com/letsar/flutter_slidable/pull/339

**Comment by zzterrozz** [comment]
@letsar please accept PR

**Comment by mark8044** [comment]
We need you @letsar lol

**Comment by letsar** [comment]
fixed in 1.2.1
