### ISSUE TITLE
Allow fitting text instead of ellipsis

### ISSUE THREAD

**Issue by LuisMiguelSS** [letsar/flutter_slidable#342]
If the text `(String label)` of an `SlidableAction` is bigger that what can be fit, the ellipsis is shown, as directed in
```dart
      children.add(
        Text(
          label!,
          overflow: TextOverflow.ellipsis,
        ),
      );
```

It would be nice to allow making the text shrink as needed, probably by adding a [FittedBox](https://api.flutter.dev/flutter/widgets/FittedBox-class.html) as asked in [this StackOverflow](https://stackoverflow.com/q/50751226/7855861) question.

I can upload a pull request if needed.

**Comment by LuisMiguelSS** [comment]
Please note that this could also be done via a `CustomSlidableAction` with a custom Widget, but may still be a nice add-in.

**Comment by letsar** [comment]
There is a ton of specialized feature request concerning `SlidableAction`. I prefer to redirect towards `CustomSlidableAction` in these case otherwise `SlidableAction` would become too complicated.
