### ISSUE TITLE
Open Slidable Action Panel on button click

### ISSUE THREAD

**Issue by akhil-ambady** [letsar/flutter_slidable#344]
I tried to use **Slidable.of(context)?.openStartActionPane();**, but it is not working. Found an answer in the FAQ section, that we can use the SlidableController to do the same. But failed to the controller in Slidable. 

Please advice.

**Comment by MRezaKarimi** [comment]
I had the same problem and [this answer](https://github.com/letsar/flutter_slidable/issues/268#issuecomment-990139555) helped me to solve it.
