### ISSUE TITLE
Lost Card effect when wrapped widget in Slidable

### ISSUE THREAD

**Issue by pushpendraKh** [letsar/flutter_slidable#348]
I have a widget that has some elevation (for card effect). I migrated from 0.6.0 to 1.1.0 and when I wrap the widget in Slidable, the card effect is gone. 

Before Migration (0.6.0) OR not wrapping the widget in Slidable
<img width="329" alt="Screenshot 2022-06-02 at 23 44 04" src="https://user-images.githubusercontent.com/11942435/171698442-620ee921-c34e-43b6-b3cc-d5b6bf206f7c.png">

After Migration to 1.1.0
<img width="330" alt="Screenshot 2022-06-02 at 23 42 22" src="https://user-images.githubusercontent.com/11942435/171698164-1c8ba3dc-a99c-44fa-b603-68ed914d785b.png">

**Comment by letsar** [comment]
Duplicates #279. Will be fixed today.
