### ISSUE TITLE
execute callback when sliding or when finishes to slide

### ISSUE THREAD

**Issue by juliovedovatto** [letsar/flutter_slidable#35]
Hello @letsar

My flutter app have a list of items (each one is a Slidable Object). I would like to execute a callback event when user start sliding the item.

My case: when I slide right to left (to show some secondary actions), I would like to hide a button in the screen. When user slide left to right (to hide secondary actions), I would like to show this button again.

![](https://media.giphy.com/media/229rpl81kmbnSr4823/giphy.gif)

I looked the source code and FAQ and didn't find anything. Am I missing something?

**Comment by letsar** [comment]
Hi @juliovedovatto 

There is nothing for this right, but I can implement something in the controller I think.

**Comment by letsar** [comment]
I can do something great with a callback that takes an animation (look at the FAB):
![slide_callback](https://user-images.githubusercontent.com/9378033/46492226-3559ae80-c80d-11e8-9a41-9984adf251d5.gif)
Do you think it will be good for you?

**Comment by juliovedovatto** [comment]
@letsar that would be great 

Well, I just need a callback event when the slide event init and when it ends. 

Something like to fire a callback when translate starts and when it finishes. Like this js lib does https://github.com/mango/slideout#events (example)

> **The slideout emits translatestart, translate and translateend events only when it is opening/closing** via touch events.

**Comment by letsar** [comment]
Hi @juliovedovatto 

I don't want to add a lot of callbacks, but I added another one to be notified when the active Slidable is open or closed.

I pushed this on this branch: https://github.com/letsar/flutter_slidable/tree/feature/35_slide_callbacks can you tell me if it's ok for you?

To use this, you need to the the `onSlideIsOpenChanged `callback on the `SlidableController`. This callback can be used like this:
``` dart
  void handleSlideIsOpenChanged(bool isOpen) {
    setState(() {
      _fabColor = isOpen ? Colors.green : Colors.blue;
    });
  } 
```

**Comment by letsar** [comment]
Published in version 0.4.8

**Comment by marcelser** [comment]
Actually the usage instructions don't work neither the ones you provided here nor the slightly more extensive ones in the documentation where it states
```dart
final SlidableController slidableController = SlidableController(
  onSlideAnimationChanged: handleSlideAnimationChanged,
  onSlideIsOpenChanged: handleSlideIsOpenChanged,
  );
...
  void handleSlideAnimationChanged(Animation<double> slideAnimation) {
    setState(() {
      _rotationAnimation = slideAnimation;
    });
  }

  void handleSlideIsOpenChanged(bool isOpen) {
    setState(() {
      _fabColor = isOpen ? Colors.green : Colors.blue;
    });
  }
```
the problem is that handleSlideAnimationChanged and handleSlideIsOpenChanged need to be static methods in the SlidableController Initializer and when you make them static of course you cannot use setState() anymore which makes it impossible to update the screen (or any widget)

Please provide working example of this. It would be greatly appreciated as I'm trying to implement it currently but I'm stuck here completely.

**Comment by arpitjacob** [comment]
Hi I am looking for a solution to this as well tried to follow the instructions but the code doesn't seem to work.

**Comment by Darren-FanDemand** [comment]
Just to add to these voices, this still doesn't work.

**Comment by MarsGoatz** [comment]
https://github.com/letsar/flutter_slidable/issues/156#issuecomment-679858293
```onSlideIsOpenChanged``` is being triggered if I provide ```onSlideAnimationChanged```. So for now as a workaround, I am providing a dummy ```onSlideAnimationChanged```.

**Comment by lane-faison** [comment]
@letsar , the `Slidable` widget is still in an active state if you slide it open and then slide it closed without lifting your finger. Can you update the package to call `.close()` when `isOpen` (`handleSlideIsOpenChanged(bool isOpen)...` is changed to `false`?

**Comment by letsar** [comment]
@lane-faison The package has completely be rewritten, can you test it in the preview version to see if it's still occurs?

**Comment by adnanjpg** [comment]
Hi, what's the status on this?
