### ISSUE TITLE
onPressed inside SlidableAction showing error

### ISSUE THREAD

**Issue by defemz** [letsar/flutter_slidable#352]
I am trying to implement onPressed inside of SlidableAction but it is not working. It is showing error "invalid constant" whenever i supply a function name(doNothing) to onPressed. I want to know how to call a function from the onPressed inside the SlidableAction. The following is what i have been doing:

```
                    SlidableAction(
                      onPressed: doNothing,
                      backgroundColor: Color(0xFF21B7CA),
                      foregroundColor: Colors.white,
                      icon: Icons.share,
                      label: 'Share',
                    ),
```

Any help will be appreciated. Thanks

**Comment by Artem2908** [comment]
Check if you have the `const` before Slidable widget. You probably created a `const Slidable(...)` widget. If so, just remove the const
