### ISSUE TITLE
icon only IconSlideAction

### ISSUE THREAD

**Issue by mike623** [letsar/flutter_slidable#36]
if caption is empty. it will occupied the space?

**Comment by letsar** [comment]
Hi, if the caption is empty, it will look like this:
![image](https://user-images.githubusercontent.com/9378033/46623117-f2f5e180-cb2c-11e8-9f3a-61388beddecc.png)

**Comment by mike623** [comment]
Ya. it is what I saw. I wonder if center the icon when caption missed is
better idea?. But currently not a problem. I copied a set can created
another new actionButton
Thanks anyway

**Comment by letsar** [comment]
Ok, I'm closing this then.

**Comment by ImaginationHub** [comment]
Duplicate a new set could solve the problem, could we have an option to disable caption? 
I want to keep the plugin as original set, so that upcoming update won't affect my app.
