### ISSUE TITLE
ClipBehavior cannot be none

### ISSUE THREAD

**Issue by iJack93** [letsar/flutter_slidable#361]
Goodmorning,

I love your library and you're doing a great job with it!
Just to let you know: I've noticed that in your custom SizeTransition class at line 147 there is the following operation to not clip when the sizeFactor is 1:

https://github.com/letsar/flutter_slidable/blob/b4e78dedf43669f10f5c4564ccef8d4c5f29713d/lib/src/dismissal.dart#L147

Setting the clipBehavior to none will cause the application to crash because the assert at line 680 of the flutter (package:flutter/src/widgets/basic.dart:680:12) will fail.
It is also stated in the ClipRect -> clipBehavior property documentation that the clipBehavior cannot be set to none or null.

I think that the solution is to leave the clipBehavior property to "hardEdge" or find another solution.

Glad to help and sorry if I did not meed the GitHub guidelines.
Thanks for the attention to this issue and keep doing a great job with this library!

**Comment by lwd369** [comment]
I've encountered the same issue.

**Comment by sara010** [comment]
Another exception was thrown: 'package:flutter/src/widgets/basic.dart': Failed assertion: line 680 pos 12: 'clipBehavior != Clip.none': is not true.

**Comment by Addadahine91** [comment]
Also getting this issue. Per the documentation, clipBehaviour must not be set to null or Clip.non - it defaults to Clip.hardEdge

https://api.flutter.dev/flutter/widgets/ClipRect/clipBehavior.html

**Comment by saigopin** [comment]
i am also getting same issue.

**Comment by arjunkn** [comment]
Cannot even run simple example because of this issue

**Comment by schigabiga** [comment]
i am also getting the same issue

**Comment by lilongcnc** [comment]
i am also getting the same issue

**Comment by RobertoMdz** [comment]
The same issue here
![Captura de Pantalla 2022-07-13 a la(s) 15 30 28](https://user-images.githubusercontent.com/61483018/178828767-63a4cd36-2f39-4ab9-be12-d2d09f239ede.png)

**Comment by lilongcnc** [comment]
您好，你的邮件我已收到。我尽快处理的哈~~么么哒~~~

**Comment by ChalermchaiPohek** [comment]
> i am also getting the same issue. With version: 1.3.0 it's working fine.
> 
> ```
> dependencies:
>   flutter_slidable: 1.3.0
> ```

This solution is work, for me.

**Comment by letsar** [comment]
Which version of flutter do you use? Seems to be ok with Flutter 3.0 ([#95593](https://github.com/flutter/flutter/pull/95593)). Maybe I should upgrade the SDK constraints

**Comment by Addadahine91** [comment]
Must be it! I’m on 2.5… my company isn’t prepared to update to 3.0 yet. Is there anything you can change in the meantime so it works with both 2.5 and 3.0? Would be ever so grateful

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by letsar** [comment]
> any update ?? im using flutter 2.8.1

I've just answered 12 minutes ago!!!
