### ISSUE TITLE
How to use onPressed?

### ISSUE THREAD

**Issue by aeg6430** [letsar/flutter_slidable#362]
As the title,how to use onPressed function?
I had tried onPressed:(){  }  and  onPressed:() but they doesn't worked:(

             `SlidableAction(

              backgroundColor: Color(0xFF0392CF),
              foregroundColor: Colors.white,
              icon: Icons.save,
              label: 'Save',
              onPressed:(){
               debugPrint('Button Save Clicked');
              },

            ),`

**Comment by letsar** [comment]
The signature is a void Function(BuildContext) so just do: 
```
SlidableAction(
  backgroundColor: Color(0xFF0392CF),
  foregroundColor: Colors.white,
  icon: Icons.save,
  label: 'Save',
  onPressed:(_){
   debugPrint('Button Save Clicked');
  },
),`  
```
