### ISSUE TITLE
Set SlidableController.activeState.open() with onTap

### ISSUE THREAD

**Issue by DARdk** [letsar/flutter_slidable#39]
Thank you for an awesome Flutter implementation!
Is it possible to open the drawer and show all the iconslider actions through a onTap event on the Slidable? See the scenario on the two images below:
![screenshot](https://user-images.githubusercontent.com/25769058/47668745-8dd06180-dba9-11e8-885d-6daad2f8a15b.png)

Currently the only example that is given is to close the drawer as seen in Issue 33:
https://github.com/letsar/flutter_slidable/issues/33
However, if the Slidable is not in an activestate, the output of: 
slidableController.activeState is null, and hence I am not able to do:
slidableController.activeState.open() because it will simply say: 
"The method 'open' was called on null" 

See the example code below:
![codeexample](https://user-images.githubusercontent.com/25769058/47668388-95433b00-dba8-11e8-998e-5eac5d59deac.png)

**Comment by letsar** [comment]
I see. This widget wasn't created with this kind of feature in mind. I need to rewrote some parts in order to be animated by sliding or with a call to a function.
For the moment, you can call `Slidable.of(context)` inside the child of a Slidable to get its state and call open(). But you won't get any animation and you won't be able to tell whether you want to open the primary or secondary actions.
I won't be able to do it now, but give me some time and I will do it 🙂.

**Comment by DARdk** [comment]
Thank you for the prompt answer letsar. 
I did not have any luck with your suggestion (my child of  ```Slidable``` is a  ```ListTile```). The ```Slidable.of(context)``` was null in all cases. 
However, I will just implement a in-app guidance, and keep this functionality as a future feature. Thank you for considering this enhancement in a future version.

**Comment by letsar** [comment]
If `Slidable.of(context)` was null, it's maybe because the context is a parent of the Slidable. It can be related to 
https://stackoverflow.com/questions/51304568/scaffold-of-called-with-a-context-that-does-not-contain-a-scaffold/51304732

Thank you, I will keep you posted on my advancement 🙂 .

**Comment by miDeb** [comment]
I've implemented a solution for this on my fork, so if you could have a look...
Note that I've also made some other changes.
Perhaps I've broken something😁.

**Comment by DARdk** [comment]
Amazing! Thanks both. I added your version to my ```pubspec.yaml```, and change from ```Slidable``` to ```Slidable.builder```. Then wrapped the child of ```Slidable.builder``` inside a builder like:
```child: new Builder(
                      builder: (contextNew) => new Column(....)```
And it perfectly animates the slide-effect for my secondaryactions during ```onTap```. 
However, somehow I need to slide it the first time to make it "recognize" the object, THEN a onTap will slide it out. But If I entered the page and directly press it: Nothing happens... Any clue? 
Thanks a lot.

**Comment by letsar** [comment]
Great. I've been working on a complete refactor of the API (you can see the work in progress in the https://github.com/letsar/flutter_slidable/tree/feature/refactor branch) and I added the feature to animate on when opening. I will keep you posted on the advancement.

**Comment by miDeb** [comment]
@DARdk are you calling open() without the actionType?

**Comment by DARdk** [comment]
@miDeb Yes, I did not add the actionType. By adding it as: ```Slidable.of(context).open(actionType: SlideActionType.secondary)```;
It works every time! Thanks, this is perfect

**Comment by enzoftware** [comment]
@DARdk thanks so much, you save me!

**Comment by ZionPi** [comment]
How to check if the `Slidable` Item is opened or closed?

**Comment by letsar** [comment]
Closing as this is resolved

**Comment by armandojimenez** [comment]
How can I check if the slideable is already open to close it?

**Comment by saigopin** [comment]
@armandojimenez any solution?

**Comment by armandojimenez** [comment]
I use this:
`if (Slidable.of(context)!.renderingMode ==
                                          SlidableRenderingMode.none) {
                                        Slidable.of(context)!.open(
                                            actionType:
                                                SlideActionType.secondary);
                                      } else {
                                        Slidable.of(context)!.close();
                                      }`

When I tap the cell, it opens or close depending if it's already open. When it closes, it does without the animation, but still work

**Comment by gopibathini** [comment]
@armandojimenez  what should instead of rendering mode in latest null satety version 1.0.0. I want to open the slider at a time on  tapping the list item , when i tap on second  item , first item just closes its slide but second item not opening it slide
