### ISSUE TITLE
Close slidable after tab on SlideAction

### ISSUE THREAD

**Issue by iPieter** [letsar/flutter_slidable#4]
In iOS, clicking on a button will also close the slidable. This makes sense, since for example deleting a record will result in the next row being displayed in the slidable otherwise.

**Comment by letsar** [comment]
I plan to add a controller to open/close a `Slidable`. This could be a part of this.
In the meantime, I think you can avoid this pitfall by setting a different key for each `Slidable`. Then when you delete a record, the list will sync if keys instead of indexes.

**Comment by letsar** [comment]
Published in version 0.3.0
