### ISSUE TITLE
Any way to make the border of the slideable more round?

### ISSUE THREAD

**Issue by lastnameswayne** [letsar/flutter_slidable#43]
Hello!

I want to use slideable on a list of cards, but since the Card Widget has a rounder border than the slidable Widget, it looks very odd. I originally wanted to make a fork that had the correct border with elevation and more "round" edges, but I can't find the lines where you define the border of the slidable. I therefore do not know what to change. I know it is a small issue, but any help is still greatly appreciated. Thanks in advance.

**Comment by RocketStormNet** [comment]
> Hello!
> 
> I want to use slideable on a list of cards, but since the Card Widget has a rounder border than the slidable Widget, it looks very odd. I originally wanted to make a fork that had the correct border with elevation and more "round" edges, but I can't find the lines where you define the border of the slidable. I therefore do not know what to change. I know it is a small issue, but any help is still greatly appreciated. Thanks in advance.

Hi!

I think I found solution. Check your (ANY)Delegate class in your slidable.dart

`
class SlidableBehindDelegate extends SlidableStackDelegate {
  const SlidableBehindDelegate({
    double fastThreshold,
  }) : super(
          fastThreshold: fastThreshold,
        );

  @override
  Widget buildStackActions(BuildContext context, SlidableDelegateContext ctx) {
    return new Positioned.fill(
      child: new LayoutBuilder(builder: (context, constraints) {
        return new Stack(
          children: <Widget>[
            ctx.createPositioned(
              position: 5.0, // WAS 0.0, TWEAK THIS TO FIND THE BEST OFFSET FOR YOUR UI
              extent:
                  ctx.getMaxExtent(constraints) * ctx.state.totalActionsExtent,
              child: new Flex(
                direction: ctx.state.widget.direction,
                children: ctx
                    .buildActions(context)
                    .map((a) => Expanded(child: a))
                    .toList(),
              ),
            ),
          ],
        );
      }),
    );
  }
}`

**Comment by RocketStormNet** [comment]
> Hello!
> 
> I want to use slideable on a list of cards, but since the Card Widget has a rounder border than the slidable Widget, it looks very odd. I originally wanted to make a fork that had the correct border with elevation and more "round" edges, but I can't find the lines where you define the border of the slidable. I therefore do not know what to change. I know it is a small issue, but any help is still greatly appreciated. Thanks in advance.

Hi!

I think I found solution. Check Delegate class that you use in your slidable.dart

```
class SlidableBehindDelegate extends SlidableStackDelegate {
  const SlidableBehindDelegate({
    double fastThreshold,
  }) : super(
          fastThreshold: fastThreshold,
        );

  @override
  Widget buildStackActions(BuildContext context, SlidableDelegateContext ctx) {
    return new Positioned.fill(
      child: new LayoutBuilder(builder: (context, constraints) {
        return new Stack(
          children: <Widget>[
            ctx.createPositioned(
              position: 5.0, // WAS 0.0, TWEAK THIS TO FIND BEST OFFSET FOR YOUR UI
              extent:
                  ctx.getMaxExtent(constraints) * ctx.state.totalActionsExtent,
              child: new Flex(
                direction: ctx.state.widget.direction,
                children: ctx
                    .buildActions(context)
                    .map((a) => Expanded(child: a))
                    .toList(),
              ),
            ),
          ],
        );
      }),
    );
  }
}
```

**Comment by letsar** [comment]
For the refactoring:
Make sure action panes are clipped

**Comment by letsar** [comment]
This is now possible in 1.0.0. I will close this ticket. If you have any issue, please open a new one.
