### ISSUE TITLE
How to setup the Slidable to occupy 1/4 or 1/8 instead of 1/2 of the size the Widget applied to Slidable?

### ISSUE THREAD

**Issue by Victorcorcos** [letsar/flutter_slidable#432]
I have this

<img width="777" alt="Screen Shot 2023-06-23 at 01 59 48" src="https://github.com/letsar/flutter_slidable/assets/7637806/901a81e8-c2d1-46a7-b1e4-029a748274f0">

But I want this

<img width="789" alt="Screen Shot 2023-06-23 at 01 59 54" src="https://github.com/letsar/flutter_slidable/assets/7637806/2ae83c85-3477-462c-aa68-b7dc4a25b2ce">

How can I do it?

⚠️ I tried to wrap `SlidableAction` into a `Container` with `width: 80`, but that huge blank space appears.

<img width="769" alt="Screen Shot 2023-06-23 at 02 03 35" src="https://github.com/letsar/flutter_slidable/assets/7637806/3c13acbd-b5b1-4cae-bc6e-4deeb16aa936">

Looks like the `Slidable` widget is always occupying **half of the size** of the Widget that it surrounds... 😱 

I want `Slidable` to occupy just _1/4_ or _1/8_ instead of _1/2_ of the size the Widget applied to Slidable.
Is it possible?

**Comment by CojocaruCristi** [comment]
On ActionPane use extentRatio param
https://stackoverflow.com/questions/71793578/flutter-package-slidable-width

**Comment by Victorcorcos** [comment]
Thanks @CojocaruCristi 

It worked 👏 

<img width="778" alt="Screen Shot 2023-06-23 at 15 41 43" src="https://github.com/letsar/flutter_slidable/assets/7637806/9b5f3884-86b2-4591-9853-23625b4914e7">

**Comment by Victorcorcos** [comment]
Thanks @CojocaruCristi 

It worked 👏 

```rb
Slidable(
  startActionPane: ActionPane(
→   extentRatio: 0.1
[ . . . ]
```

<img width="778" alt="Screen Shot 2023-06-23 at 15 41 43" src="https://github.com/letsar/flutter_slidable/assets/7637806/9b5f3884-86b2-4591-9853-23625b4914e7">
