### ISSUE TITLE
Requests: Ripple on tap, Icon and text sizes

### ISSUE THREAD

**Issue by guyzk** [letsar/flutter_slidable#45]
Great work! Really useful

A few requests to make the package even better
1) Add a ripple effect (Inkwell) on action tap
2) Option to pass an Icon size
3) Option to send in a custom TextStyle

I know most of these options are available if using the customizable "SlideAction" widget but it would be nice if the IconSlideAction could have these additions.

**Comment by jaumard** [comment]
Feel strange to don't have any touch feedback like ripple yes

**Comment by m-sadegh-sh** [comment]
I agree with @guyzk about adding mentioned features

**Comment by letsar** [comment]
I think this is resolved now.

**Comment by acoutts** [comment]
Is it possible to disable the splash effect? sometimes I don't want a material splash in my custom theme
