### ISSUE TITLE
Activate only 1 action at a time?

### ISSUE THREAD

**Issue by NTMS2017** [letsar/flutter_slidable#46]
Hi, Thanks for great plugin. 

In my Slidable -> secondaryActions: <Widget>[ -> I have a 3 IconSlideAction. If user slides the ListTile it shows this 3 IconSlideAction widget. If I tap same time to 2 or 3 icons its opens all of them. I have to close 1 by 1. again if accidentally press between 2 icon it opens both. How can activate 1 action at a time? Thanks

**Comment by letsar** [comment]
I think this is resolved by now.
