### ISSUE TITLE
How to set the slider extent?

### ISSUE THREAD

**Issue by delfme** [letsar/flutter_slidable#469]
Hello @letsar 
Thx for this great plugin.
Is there a quick way to declare the slide motion extent?

Please see pic below, we would need a property to set the width for 1 (or for 2), so that we could control the space that will be given to the slider commands.

![IMG_5282](https://github.com/letsar/flutter_slidable/assets/53510751/30d8247d-a2ac-4c22-9335-22ee823240af)

**Comment by iosephmagno** [comment]
Found the answer. Closing this.

**Comment by delfme** [comment]
Found the answer. Closing this.

**Comment by Hellomik2002** [comment]
Where ?

**Comment by ttsakalos** [comment]
> Where ?

You can set the width by utilizing the `extentRatio` attribute. For example:
`extentRatio: 0.15` is approximately 82 logical pixels.
