### ISSUE TITLE
onTap doesn't work

### ISSUE THREAD

**Issue by ndemari** [letsar/flutter_slidable#47]
Adding a callback function for IconSlideAction to onTap doesn't work no matter what I do.

**Comment by ignertic** [comment]
It seems it's triggered when the widgets build, really need solution to this

**Comment by ignertic** [comment]
was this ever solved?

**Comment by letsar** [comment]
Cannot reproduce, I'm closing this. If there's still an issue for you, please fill an new issue with the exact steps how to reproduce this.
