### ISSUE TITLE
Icon only slide action without occupying space

### ISSUE THREAD

**Issue by ImaginationHub** [letsar/flutter_slidable#49]
Hi,

Thanks very much for the great plugin! 

Could we have an option to disable caption without occupying space?
If caption is empty, the vertical alignment of icons looks weird.

Below image shows the different, the red horizontal line helps to sort the problem.

![action button alignment](http://61.238.254.110/icon_slide_action.jpg)

Thanks
Imagination

**Comment by letsar** [comment]
Hi, thanks for using this package. `SlideAction` is only intended to help people to easily create actions. If the current behavior doesn't fit your needs, you can always create your own buttons.
