### ISSUE TITLE
SlidableController not closing other slidable items

### ISSUE THREAD

**Issue by tidharnitzan** [letsar/flutter_slidable#52]
hi, it doesn't seem to work.
while I defined it correctly in the ctor I can still open several items and they all remain opened (I expected the other to auto close when another one is opened).
![image](https://user-images.githubusercontent.com/7069401/53364019-8ac26380-3946-11e9-9f89-04ab39189caa.png)

code:
...
final SlidableController slidableController = new SlidableController();
...
child: Slidable(
key: Key(_row.animalID),
controller: slidableController,
delegate: new SlidableBehindDelegate(),
actionExtentRatio: 0.25,
secondaryActions: [

....

**Comment by devashish-patel** [comment]
Any updates on this?
Same issue for me as well...

**Comment by werytert** [comment]
soooo... Any updates?

**Comment by tidharnitzan** [comment]
Worked for me very good.

**Comment by werytert** [comment]
@tidharnitzan Sorry, it's was only my mistake

**Comment by m-sadegh-sh** [comment]
I have also same issue with SlidableController :( I'm using Redux so there is no stateful widget at all in my application. This can be the cause of this error?

**Comment by cheasonxie** [comment]
All slidables must share the same controller , so you should define controller as class member instead of in method variable.
class YourWidgetState extends State<YourWidget> {
  SlidableController _slidableController = new SlidableController();
  ...
  @override
    Widget build(BuildContext context) {
       ...
        child: Slidable(
              key: Key(_row.animalID),
             controller: _slidableController ,
             delegate: new SlidableBehindDelegate(),
             actionExtentRatio: 0.25,
             secondaryActions: [
             ...

**Comment by julianbraasch** [comment]
@cheasonxie I have it set up this way but I am still able to open multiple Slidables.

**Comment by letsar** [comment]
@cheasonxie is right, you must provide the same SlidableController to all slidables if you want them to close when another one opens.
