### ISSUE TITLE
Changing of SlideAction' size

### ISSUE THREAD

**Issue by nodahikaru** [letsar/flutter_slidable#53]
It seems width of SlideAction is static. I tried to change width of SlideAction by changing child' Container width. But it doesn't work for me.
Is there any way to change width of SlideAction?

**Comment by pradeepkarth** [comment]
change ` const double _kActionsExtentRatio = 0.25; ` in slidedable.dart to 
` const double _kActionsExtentRatio = 0.1; `.

**Comment by zhangxu123123** [comment]
Is there any way to change height of SlideAction?

**Comment by letsar** [comment]
For the moment you have to set a ratio. I'm working on a code refactoring so that you it will be more flexible.

**Comment by letsar** [comment]
In 1.0.0, you can now set a different size for each action. I will close this ticket. If you have any issue, please open a new one.
