### ISSUE TITLE
Slidable prevent all other swipe action

### ISSUE THREAD

**Issue by jaumard** [letsar/flutter_slidable#54]
If you use this plugin into a tabView, you'll not be able to swipe to change tab, even if you use only one side of Slidable. It should not stop propagation of swipe event if no action is define for the given orientation

**Comment by kw2019ltd** [comment]
same issue for me we need solution for it.

**Comment by Shakle** [comment]
you can create an invisible Container on the left side above the slidable in stack and drag it.
Stack(
Slidable(),
Container(color: Colors.transparent, width: MediaQuery.of(context).size.width * 0.027),
)

**Comment by JeffersonCarvalh0** [comment]
I'm experiencing the same issue here. The invisible container mentioned above didn't work for me.

**Comment by JeffersonCarvalh0** [comment]
Could it be a problem in flutter itself?
https://github.com/flutter/flutter/issues/24233

**Comment by letsar** [comment]
We should not mix two components with the same scroll direction on the same view. In my opinion this will always lead to issues.
