### ISSUE TITLE
onTap doesnt close properly slider when calling setState in it

### ISSUE THREAD

**Issue by pbouttier** [letsar/flutter_slidable#57]
Hi,

When i call setState on onTap, the slider close promptly, and not by sliding back.

`IconSlideAction(
          caption: 'Modifier',
          color: spYellow,
          icon: Icons.create,
          onTap: () {
            setState(() {
              titleController.text = session.title;
            });
            showDialog(
                context: context, child: popupUpsertSession(session, _update)
            );
          },
        )`

It's a minor detail, but if you can fix it,

Have a nice day !

**Comment by letsar** [comment]
I think it's resolved now.
