### ISSUE TITLE
Max width of the action

### ISSUE THREAD

**Issue by kostasoft** [letsar/flutter_slidable#61]
Hello! Thank you very much for the library!
There is a question: is it possible to limit the width of the action?
With a wide screen and the parameter actionExtentRatio: 0.25, the actions are very wide.

**Comment by pradeepkarth** [comment]
change `const double _kActionsExtentRatio = 0.25;` in slidedable.dart to
`const double _kActionsExtentRatio = 0.1;`

**Comment by letsar** [comment]
A code refactoring is in progress to make Slidable more flexible. For now, you cannot set a fixed extent.

**Comment by letsar** [comment]
This is now possible in 1.0.0. I will close this ticket. If you have any issue, please open a new one.
