### ISSUE TITLE
Two showAllActionsThreshold: (one for opening and one for closing)

### ISSUE THREAD

**Issue by msw333** [letsar/flutter_slidable#62]
From my point of view, opening the slideable is at first not pretty ease (if you compare it to WhatsApp / Telegram), but it gets wonderful smooth if I set `howAllActionsThreshold: 0.20`. Is there a same kind of threshold for swiping the items back in? Guess we need two thresholds then?

**Comment by BouncyButton** [comment]
Hello msw333,
I think you're right 😃 
I opened the slidable.dart file and monkey-patched the `_handleDragEnd` function as follows, right after the dismiss state check:
```
else if (_overallMoveController.status != AnimationStatus.reverse) {
      // is it closing?
      if (_actionsMoveAnimation.value >= widget.showAllActionsThreshold) {
        close();
      }
    }
```

It seems to work as you intended now.
Let me know if there's a better solution, I just started with Flutter a few days ago.

**Comment by letsar** [comment]
I have to test this, and make it and the code refactoring I'm going to do! Thanks.

**Comment by cassioseffrin** [comment]
@letsar,  any news on this? May I can fix it if you are accepting PRs?

**Comment by letsar** [comment]
Yes, can you test the revival branch to see if what you want has been implemented in the refactoring?

**Comment by letsar** [comment]
This is now possible in 1.0.0. I will close this ticket. If you have any issue, please open a new one.
