### ISSUE TITLE
dismissal null or not set make slidable feature/refactor crashed

### ISSUE THREAD

**Issue by thanhhuan1990** [letsar/flutter_slidable#65]
I trying to make function slidable item's open() work by click on button so I changed to use branch feature/refactor, but this branch require init Slidable with dismissal, without this it crashed with below log.

E/flutter: [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
    NoSuchMethodError: The method '[]' was called on null.
    Receiver: null
    Tried calling: [](Instance of 'SlideActionType')
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
    #1      SlidableState._dismissThreshold (package:flutter_slidable/src/widgets/slidable.dart:562:42)
    #2      SlidableState.build (package:flutter_slidable/src/widgets/slidable.dart:897:27)
    #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
    #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
    #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
    #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
    #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
    #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
    #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
    #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
    #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
    #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
    #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
    #14     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
    #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
    #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
    #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
    #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
    #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
    #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
    #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
    #22     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
    #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
    #24     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1034:36)
    #25     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:984:34)
    #26     List.forEach (dart:core-patch/growable_array.dart:278:8)
    #27     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:995:36)
    #28     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:961:7)
    #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
    #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
    #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
    #32     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
    #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
    #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
    #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
    #36     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
    #37     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
    #38     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
    #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
    #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
    #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
    #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
    #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
    #44     SingleChildRenderObjectElement.update (pack

Please help me, thanks

**Comment by Shakle** [comment]
Same thing after 5.0
Tried calling: [](Instance of 'SlideActionType')

`return Slidable(
      actionPane: SlidableDrawerActionPane(),
      actionExtentRatio: 0.25, secondaryActions: (Api.answers[index]['stat'] == 'unread') ? <Widget>[
        IconSlideAction(
          caption: 'Прочитано',
          color: Colors.blue,
          icon: Icons.done,
          onTap: () async {
            await Api.answerRead(Api.answers[index]['cid']);
            Api.answers.removeAt(index);
            Scaffold.of(context).showSnackBar(SnackBar(content: Text("Комментарий прочитан")));
            await Api.getUserAnswers();
            setState(() {});
          }
        ),
        IconSlideAction(
          caption: 'К статье',
          color: Colors.indigo,
          icon: Icons.chrome_reader_mode,
          onTap: () async {
            Navigator.push(context, MaterialPageRoute(builder: (context) =>
                Article(isFavorite: 1, index: 0356,
                    pid: int.parse(Api.answers[index]['pid']), cid: int.parse(Api.answers[index]['cid']))));
            await Api.answerRead(Api.answers[index]['cid']);
            Api.answers.removeAt(index);
            await Api.getUserAnswers();
            setState(() {});
          }
        ),
      ]`

**Comment by GoodZMJ** [comment]
Hello,Has this problem been solved?I don't want to slide delete so how do I disable that

**Comment by letsar** [comment]
I think it's resolved now. Please create a new issue if you don't think it is.
