### ISSUE TITLE
Programmatically open slider

### ISSUE THREAD

**Issue by brotoo25** [letsar/flutter_slidable#67]
Would like to present the side buttons to the user for a little while and then close it, all without any touch interactions.

**Comment by geekydiamond** [comment]
Or just a little peek so the user knows that there are buttons available via slide

**Comment by spedalilama** [comment]
Any update on this?  I'm looking to do the same thing.

**Comment by vladbarash** [comment]
The readme has a note about doing this:

> You can open or close the Slidable programmatically by calling the open or close method of the SlidableState. The easiest way get the SlidableState from a child is to call Slidable.of(context).
> 
> The open method has an optional parameter called actionType that let you choose which action pane to open.

However, I was not able to figure it out with these details. Has anyone been able to get this working?

**Comment by irishka90** [comment]
if i have a few sliders on screen (widget with slider  and listview with sliders) can you give me example.
 Call Slidable.of(context) always return  null

**Comment by vladbarash** [comment]
@irishka90 I am experiencing the same issue, not able to figure it out using the documentation.

**Comment by Brazol** [comment]
I created a fork with peek option for Slidable. Just set _peekOnInit_ and _peekActionType_. Maybe it will help someone.

https://github.com/Brazol/flutter_slidable

**Comment by mjeffw** [comment]
For those having trouble with Slidable.of(context) returning null, refer to this issue:

https://github.com/letsar/flutter_slidable/issues/95

**Comment by tigrenok00** [comment]
Did anyone find a solution? I can close the slider via controoller.activeState?close() if it is open, however, the open() method does not work the same way for some reason

**Comment by brotoo25** [comment]
> Did anyone find a solution? I can close the slider via controoller.activeState?close() if it is open, however, the open() method does not work the same way for some reason

Slidable.of(context).open(
     actionType: SlideActionType.secondary,
);

Works for me.

**Comment by Purvik** [comment]
@brotoo25  I got that this is the way to programmatically open and close but what If I'm passing Function from its parent widget tree and assigning it's directly to onPress or onClick of action icon. How can I perform close?

**Comment by ArthurDevv** [comment]
> I created a fork with peek option for Slidable (in peek feature branch). Just set _peekOnInit_ and _peekActionType_. Maybe it will help someone.
> 
> https://github.com/Brazol/flutter_slidable/tree/feature/peek

I tried using your fork. It didn't work either.
Could you provide an example on how to implement it or is it just a simple matter of setting the peekOnInit parameter to true?

**Comment by letsar** [comment]
I think, this is now possible in the 1.0 version. You can get the SlidableController within a Slidable's child and make some actions programmatically.

**Comment by mflesh1** [comment]
Is there a working example of how to use the SlideableController?
