### ISSUE TITLE
How to change a Silidable child's textstyle when it closes or opens

### ISSUE THREAD

**Issue by Siwuji** [letsar/flutter_slidable#68]
How to change a Silidable child's textstyle when it closes or opens?

**Comment by Siwuji** [comment]
I want to change it's color when it open , but i always change all children's color .
How to distinguish them？

**Comment by XinleZhou2018** [comment]
Hi, do you solve this problem?

**Comment by letsar** [comment]
I will see how to make this easier with the new refactoring.

**Comment by reidterror** [comment]
Any updates on this?

**Comment by letsar** [comment]
On 1.0 you can get the SlidableController within any Slidable's child (Slidable.of(context)). With this controller you listen to some notifiers and do what you want.
