### ISSUE TITLE
What should I do if I want to hide ations after clicking on the action?

### ISSUE THREAD

**Issue by renhaoweixiao** [letsar/flutter_slidable#7]

**Comment by letsar** [comment]
For now you can't. I plan to create a `SlidableController` (#6) in order to allow this among other things.

**Comment by letsar** [comment]
I think I will take time to think about how to create a `SlidableController` to avoid some pitfalls. In the meantime I will implement some feature to allow a slide action to close its nearest `Slidable`.

**Comment by letsar** [comment]
This now by default in the version 0.3.0
