### ISSUE TITLE
Icon Slide Action ontap not working

### ISSUE THREAD

**Issue by Raviteja11122** [letsar/flutter_slidable#73]
Hi,

I'm using only secondary actions in that only second IconSlideAction ontap is working first one is not working

**Comment by ampersand-dev** [comment]
me too ! help me !!

**Comment by Raviteja11122** [comment]
https://stackoverflow.com/questions/46651974/swipe-list-item-for-more-options-flutter

Use this custom class SlideMenu.

![Screenshot from 2019-05-20 12-24-29](https://user-images.githubusercontent.com/49988053/58001845-505a0400-7afa-11e9-880a-549fe61e21dc.png)

**Comment by letsar** [comment]
It's seems to not working only with SlidableDrawerActionPane. I don't know why for now

**Comment by letsar** [comment]
Fixed in v0.5.1
