### ISSUE TITLE
Can't use only 1 action

### ISSUE THREAD

**Issue by marianoarga** [letsar/flutter_slidable#74]
As title describes, if you only use 1 action, the space for 2 actions is allocated anyway, result in a strange behavior

**Comment by qutz** [comment]
actionPane use SlidableBehindActionPane、SlidableScrollActionPane、SlidableStrechActionPane
actionPane  not use SlidableDrawerActionPane

**Comment by kenthinson** [comment]
actionPane: SlidableStrechActionPane(),

**Comment by marianoarga** [comment]
Thank you all.

**Comment by letsar** [comment]
Fixed in v0.5.3
