### ISSUE TITLE
Close slidable on unfocus

### ISSUE THREAD

**Issue by QuentinG3** [letsar/flutter_slidable#76]
Hi,

Would it be possible to a parameter closeOnUnfocus to close de slidable when tapping anywhere else on the screen?

Or is there another clean way to do this?

Thank you

**Comment by comm1x** [comment]
Yes, this behavior is default in iOS. It is absolutely must have.

**Comment by kuntojirohan** [comment]
Can anyone please let me know how to deal with this issue? I have a list of slidable cards with Listview, and I want to close the (left or right) slid card when another card is slid or if I tap anywhere else on the screen.

**Comment by subinsuresh** [comment]
Any updates on this issue?

**Comment by subinsuresh** [comment]
Worked for me, 
SlidableController slidableController = SlidableController();

Set controller property of Slidable with slidableController,
Slidable(
      actionPane: SlidableDrawerActionPane(),
      actionExtentRatio: 0.3,
      **controller: slidableController,**

Add below code onTap function of listview item.
if(slidableController.activeState != null){
     slidableController.activeState.close();
 }else{
   //Write your business logic in item click.
}

**Comment by letsar** [comment]
Follow @subinsuresh comment for now.

**Comment by reidterror** [comment]
My page wont be full of times most of the time, any updates on this one?
