### ISSUE TITLE
SlidableController losing activeState when the item widget refreshes

### ISSUE THREAD

**Issue by rmarau** [letsar/flutter_slidable#78]
Hi @letsar 

I'm composing a list of Slidable with ExpansionTile.
In a sequence of events where I 
- open the primaryActions (say for item no1)
- tap an Action (with closeOnTap: false,)
- In the tap handler: order a Tile expand
- If I then slide another item (say no2) it slides but it won't close item 1.

This happens because expanding the tile forces the Slidable's state to pass on didUpdateWidget and dispose.

And when disposing: there's this line that clears the SlidableState and this is irreversible.
https://github.com/letsar/flutter_slidable/blob/9bf12c2e5e12614eabea7f9cc42157ec837b6a7b/lib/src/widgets/slidable.dart#L627

When the updated state lands (newWidget) the slider is correctly open (I have set closeOnTap: false) but the controller's state is not in sync.

Is it really necessary that controller's state clearing? Removing that single lineI works fine in my case. But I might be missing some cases that your covering.

**Comment by letsar** [comment]
Thank you for this issue. I will keep it in mind for my refactoring

**Comment by rmarau** [comment]
I no longer see this issue with v0.6.0.
Updating to 1.x will take some care.
