### ISSUE TITLE
Are there any examples of using the "more" option?

### ISSUE THREAD

**Issue by warriorCoder** [letsar/flutter_slidable#82]
Just wondering if there are any examples or suggestion on best practices when using the more build in option.

**Comment by kenthinson** [comment]
When in doubt loo to native apps. Here is an example from iOS mail app.
![IMG_0015](https://user-images.githubusercontent.com/2245494/64284655-b50d6300-cf1f-11e9-8fd3-f917f62ba880.PNG)
![IMG_0016](https://user-images.githubusercontent.com/2245494/64284656-b50d6300-cf1f-11e9-8ff0-1d911d883fe3.PNG)
