### ISSUE TITLE
StreamBuilder not working inside SlideAction

### ISSUE THREAD

**Issue by riccardo-lomazzi** [letsar/flutter_slidable#83]
I'd love to implement a StreamBuilder as an IconSlideAction, to see if the property of an object inside a list has changed or not. But any implementation of it is not working. It checks the snapshot for data only once, and never updates.

**Comment by verscph** [comment]
I have the same issue.

Example:
```
Slidable(
      actionPane: SlidableDrawerActionPane(),
      actionExtentRatio: 0.25,
      child: Container(
        color: Colors.white,
        child: ListTile(
          title: Text(athlete.firstName + " " + athlete.lastName),
          subtitle: Text(athlete.yearOfBirth.toString()),
          trailing: _presence(athlete.id), // which returns a StreamBuilder<QuerySnapshot> object
        ),
      ),
      actions: <Widget>[
        IconSlideAction(
          caption: 'Archive',
          color: Colors.blue,
          icon: Icons.archive,
          onTap: () => null,
        ),
        IconSlideAction(
          caption: 'Share',
          color: Colors.indigo,
          icon: Icons.share,
          onTap: () => null,
        ),
      ],
      secondaryActions: <Widget>[
        IconSlideAction(
          caption: 'More',
          color: Colors.black45,
          icon: Icons.more_horiz,
          onTap: () => null,
        ),
        IconSlideAction(
          caption: 'Delete',
          color: Colors.red,
          icon: Icons.delete,
          onTap: () => null,
        ),
      ],
    );
```
When you slide the ListTile, the trailing attribute turns into a CircularProgressIndicator and doesn't update to what the Streambuilder should return.

Before slide:
![Screenshot 2019-08-20 at 08 43 09](https://user-images.githubusercontent.com/34537296/63323832-ff3ef380-c326-11e9-8dd7-87fc8a264e84.png)

During slide:
![Screenshot 2019-08-20 at 08 41 19](https://user-images.githubusercontent.com/34537296/63323568-67410a00-c326-11e9-9d66-9bbb3503ab32.png)

After slide:
![Screenshot 2019-08-20 at 08 41 09](https://user-images.githubusercontent.com/34537296/63323889-25649380-c327-11e9-9814-9bad2edc11eb.png)

Is this a bug, or is there another way to implement this functionality?

**Comment by verscph** [comment]
Some extra input. The code to generate the output for the trailing attribute of the ListTile is:

```
return StreamBuilder<QuerySnapshot>(
      stream: presenceStream,
      builder: (context, snapshot) {
        print('into the stream');
        if (!snapshot.hasData) {
          print(snapshot.connectionState.toString());
          return CircularProgressIndicator();
        }
```
It shows this output in the console when fetching the data from the stream (2 records):
```
flutter: into the stream
flutter: ConnectionState.waiting
flutter: into the stream
flutter: ConnectionState.waiting
flutter: into the stream
flutter: Fetched: {athleteId: k9fO7fJpqvyxDFGzQpS4, eventDate: Timestamp(seconds=1566331200, nanoseconds=0)}
flutter: into the stream
flutter: Fetched: {athleteId: 5CZyqkC2eaePpWJXYN02, eventDate: Timestamp(seconds=1566331200, nanoseconds=0)}
```
So far so good.

When you slide one of the ListTile elements, the CircularProgressIndicator is shown and the console shows:
```
flutter: into the stream
flutter: ConnectionState.waiting
```

It looks like activating the slider causes the app to check the stream for updates (or send updates?), but the ConnectionState of the stream stays "waiting" instead of being activated. 

Hope this helps to figure out what goes wrong.

**Comment by verscph** [comment]
@letsar, can you pls take a look at this?

**Comment by ysoo14** [comment]
How about wrapping up the Slidable with Streambuilder? I had a same issue, but I solved the problem wrapping the Slidable with Streambuilder. Like

```return StreamBuilder(
        stream: streamSnapshots,
        builder: (context, snapshot) {
        return Slidable(
        actionPane: SlidableDrawerActionPane(),
        controller: slidableController,
        actionExtentRatio: 0.25,
        child: Container ... ```

**Comment by letsar** [comment]
I will see if this use case can be implemented with my in-progress refactoring.

**Comment by letsar** [comment]
Can you test this use case in the latest 1.0 dev preview?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
