### ISSUE TITLE
Slidable List with Padding/Margin

### ISSUE THREAD

**Issue by mamen2022** [letsar/flutter_slidable#85]
Hi,

I have a list and want to implement the slidable row in this list. Although, my list is not a full screen width list, so when i slide a row the widget overlaps the padding that I am using on the list.

![Screenshot from 2019-07-03 15-16-11](https://user-images.githubusercontent.com/9058507/60599004-9d8dee80-9da5-11e9-910b-c96a55fdd9dd.png)

How can I limit the row (red) to the list width instead of the hole screen width?

**Comment by vladbarash** [comment]
Hi @mamen2022 - can you share sample code? I had a similar question, and I solved it by using ListView.separated where you can define a separatorBuilder.

**Comment by letsar** [comment]
I will make sure this use case is taken into account in my refactoring.

**Comment by letsar** [comment]
Fixed in 1.0

**Comment by AlexanderFarkas** [comment]
Reverse question - how to force screen width in 1.0.0?

**Comment by AlexanderFarkas** [comment]
Initial question could be resolved by simple ClipRect wrapper, I suppose. For now, it's not possible to reproduce initial behaviour.
