### ISSUE TITLE
Enable / Disable

### ISSUE THREAD

**Issue by Solido** [letsar/flutter_slidable#9]
Like for form fields I need to enable/disable the slide behaviour.

**Comment by letsar** [comment]
Interesting, you can do this by settng the actions to null, but it is more simpler with a parameter indeed 😄 .
You tempt me to do this now, you know 🤣

**Comment by Solido** [comment]
Fluttorite aigue ! tu vas finir tout bleu ... ;)

**Comment by letsar** [comment]
Can you check https://github.com/letsar/flutter_slidable/tree/feature/9_enabled and tell me if it's what you had in mind?

**Comment by Solido** [comment]
Nothing happen ... this is the requested effect ! thx

**Comment by letsar** [comment]
Published in version 0.3.2
