### ISSUE TITLE
Keep state when clicking on an action?

### ISSUE THREAD

**Issue by unamed000** [letsar/flutter_slidable#90]
Hi guys.
I would like to ask if there is any default param that allow this widget to keep the actions opened as default?

I would like to implement reordering feature that when the user swipe, we will have up and down arrow, when the user click on these buttons, the widget will be re-render by using setState and the row that the user clicking on it will keep the actions opened.

Thanks :)

**Comment by letsar** [comment]
Can you test it with 1.0 version?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
