### ISSUE TITLE
Insight to issue: 'open' was called on null.

### ISSUE THREAD

**Issue by DarrylDJohnson** [letsar/flutter_slidable#91]
I am using a controller to handle the Slidable widget's open. From what I have tested, 
`close()` works well. However, open will throw the above error unless the Slideable widget is already open to one side.

In the example below, the Slidable widget opens the secondaryActions only if the primaryActions are open. Of course, the error does not occur if the secondaryActions is already open, where it arbitrarily just keeps the secondaryActions drawer open. The error is thrown when neither is open.

```
class SlidableExample extends StatefulWidget {
  @override
  _SlidableExampleState createState() => _SlidableExampleState();
}

class _SlidableExampleState extends State<SlidableExample> {
  SlidableController _controller = SlidableController();

  @override
  Widget build(BuildContext context) {
    return Slidable(
      controller: _controller,
      actionPane: SlidableScrollActionPane(),
      child: GestureDetector(
        onTap: () =>
            _controller.activeState.open(actionType: SlideActionType.secondary),
        child: ListTile(
          title: Text('title'),
        ),
      ),
      actions: <Widget>[
        new Container(),
      ],
      secondaryActions: <Widget>[
        new Container(),
      ],
    );
  }
}
```

**Comment by letsar** [comment]
Can you test your use case with 1.0 version?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
