### ISSUE TITLE
PageView turn first page

### ISSUE THREAD

**Issue by muratangin187** [letsar/flutter_slidable#92]
I used PageView as the child of Slidable. When I scroll on the second page, my current page changes to the first one.

`Slidable(
          actionExtentRatio: 0.25,
          actionPane: SlidableBehindActionPane(),
              child: PageView(
                children: <Widget>[
                  Container(
                    color: Colors.grey,
                    child: Center(
                      child: Text('ICERIK'),
                    ),
                  ),
                  Container(
                    color: Colors.cyan,
                    child: Center(
                      child: Text('ICERIK DETAY'),
                    ),
                  ),
                ],
              ),
              direction: Axis.vertical,
              actions: <Widget>[Container(
                child: Padding(padding: EdgeInsets.all(16),child: Icon(Icons.thumb_up, size: 64,),),
                alignment: Alignment.topCenter,
                decoration: BoxDecoration(
                  color: Colors.green,
                ),
              )],
              secondaryActions:<Widget>[ Container(
                child: Padding(padding: EdgeInsets.all(16),child: Icon(Icons.thumb_down, size: 64,),),
                alignment: Alignment.bottomCenter,
                width: MediaQuery.of(context).size.width,
                decoration: BoxDecoration(
                  color: Colors.red,
                ),
              )],
            ),`

**Comment by letsar** [comment]
The child of a Slidable should not be another scrolling widget in the same direction
