### ISSUE TITLE
Slidable.of(context) always returns null

### ISSUE THREAD

**Issue by mjeffw** [letsar/flutter_slidable#95]
Just what the title says. Since Slidable.of(context) always returns null, the Slidable cannot be programmatically controlled.

**Comment by mjeffw** [comment]
Some additional details that may help others:

Part of this is user error. In order for Slidable.of(context) to return something meaningful, context has to be the actual component's context, not a parent context. (Duh.) I was doing something like this:

    class MyWidget extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return Container(
          child: Slidable(
            child: ListTile(
              trailing: IconButton(
                icon: Icon(Icons.more_vert),
                 onPressed: () => Slidable.of(context).open(),
              ) // IconButton
          ) // Slidable
        ); // Container
      }
    }

Obviously this is wrong; the context used in the onPressed function is the context of MyWidget, not the context of the ListTile. Extracting the IconButton into its own widget solved this problem. Example:

    class _MoreButton extends StatelessWidget {
      const _MoreButton({
        Key key,
      }) : super(key: key);

      @override
      Widget build(BuildContext context) {
        return IconButton(
          icon: Icon(Icons.more_vert),
          iconSize: 20.0,
          onPressed: () => Slidable.of(context).open(),
        );
      }
    }

Now my original build() method becomes:

        return Container(
          child: Slidable(
            child: ListTile(
              trailing: _MoreButton(),
          ) // Slidable
        ); // Container

At this point, Slidable.of(context) indeed returns the SlidableState object.

But calling Slidable.of(context).open() still did not work. The reason for that is that the open() method only opens primary actions of the Slidable. In my case, I only have secondary actions, and thus the method fails to open those actions.

I suggest adding a SlidableState.openSecondary() method to SlidableState.

**Comment by limzhipeng-kumoten** [comment]
Slidable.of(context).open(actionType: SlideActionType.secondary);

Have you tried this method?

By default it's open the [SlideActionType.primary] action pane, but you can modify this by setting [actionType].

**Comment by alexmaycon** [comment]
> Slidable.of(context).open(actionType: SlideActionType.secondary);
> 
> Have you tried this method?
> 
> By default it's open the [SlideActionType.primary] action pane, but you can modify this by setting [actionType].

I have same problem. I tried both actions (SlideActionType.primary, SlideActionType.secondary) but none worked.

**Comment by letsar** [comment]
Can you post a complete example (or paste a link to one) so that I can test it from my side?

**Comment by mjeffw** [comment]
My problem was fixed by upgrading the flutter_slidable dependency. The one I started with did not have the actionType parameter to the open() method.

**Comment by Shantaviae** [comment]
Thanks for those tips @mjeffw , they were very helpful!

With your help, I was able to implement a 'toggle' for tap gestures with the following:

`class _SlideTile extends StatelessWidget {
  const _SlideTile({@required this.controller, Key key }) : super(key: key);

  final SlidableController controller;

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () {
        if (controller?.activeState == null)
          Slidable.of(context).open(actionType: SlideActionType.secondary);
        else
          Slidable.of(context).close();
      },
      child: Card(
        elevation: 0.0,
        child: SizedBox(height: 60),
      ),
    );
  }
}`
