### ISSUE TITLE
Close all other secondaryActions 

### ISSUE THREAD

**Issue by billy124** [letsar/flutter_slidable#98]
Hi guys,

Is there a way to close all open `secondaryActions` when a new action is open?

Thank you,
Billy

**Comment by letsar** [comment]
You just have to add a `SlidableController` to your Slidables : https://github.com/letsar/flutter_slidable#how-to-let-keep-only-one-slidable-open

**Comment by DowsingUK** [comment]
Is not working when use Slidable.builder(
      key: Key(item.id),
      controller: slidableController
      ...

Is there any way to achieve this behaviour with Slidable.builder I need the SlideActionBuilderDelegate
