### ISSUE TITLE
Max height of the action

### ISSUE THREAD

**Issue by MirzayevFarid** [letsar/flutter_slidable#99]
Hi! Thank you very much for the library!
Is it possible to limit the height of the action?

**Comment by letsar** [comment]
Hi, thank you :-).
I don't understand your question, the action should have the height of the Slidable.

**Comment by rignaneseleo** [comment]
In my case the Widget I'm sliding has a padding so it doesn't fill the whole height of a list item, while the actions have the max height. 

EDIT: I moved the margin from the list item to the list itself using [ListView.separated builder ](https://api.flutter.dev/flutter/widgets/ListView/ListView.separated.html)
